// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class EmailView : BaseView
{
    public const string NAME ="EmailView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UIGrid Grid_UIGrid;
    public UILabel ContentLabel_UILabel;
    public UILabel TitleLabel_UILabel;
    public UILabel SenderLabel_UILabel;
    public UILabel TimeLabel_UILabel;
    public UIButton GetBtn_UIButton;
    public UILabel BtnLabel_UILabel;
    public UISprite InBg_2_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BG/CloseBtn");
        TitleLabel_UILabel = root.FindScript<UILabel>("BG/TitleLabel");
        Grid_UIGrid = root.FindScript<UIGrid>("InBg_2/ScrollView/Grid");
        ContentLabel_UILabel = root.FindScript<UILabel>("ContentLabel");
        SenderLabel_UILabel = root.FindScript<UILabel>("SenderLabel");
        TimeLabel_UILabel = root.FindScript<UILabel>("TimeLabel");
        GetBtn_UIButton = root.FindScript<UIButton>("GetBtn");
        BtnLabel_UILabel = root.FindScript<UILabel>("GetBtn/BtnLabel");
        InBg_2_UISprite = root.FindScript<UISprite>("InBg_2");

    }
    #endregion
}
