// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  BattleFormationInfoViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IBattleFormationInfoViewController
{

}

public partial class BattleFormationInfoViewController:MonolessViewController<BattleFormationInfoView>, IBattleFormationInfoViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
