// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class MoneyInfoView : BaseView
{
    public const string NAME ="MoneyInfoView";

    #region Element Bindings

    /// bind gameobject
    public GameObject Anchor;
    public UIGrid Anchor_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Anchor = root.FindGameObject("Anchor");
        Anchor_UIGrid = root.FindScript<UIGrid>("Anchor");

    }
    #endregion
}
