// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class ExChangeMainView : BaseView
{
    public const string NAME ="ExChangeMainView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public GameObject tab_content;
    public GameObject PageTurnView;
    public UILabel ExpectItemTips_UILabel;
    public UISprite From_ItemIcon_UISprite;
    public UILabel From_ItemNumber_UILabel;
    public UISprite To_ItemIcon_UISprite;
    public UILabel To_ItemNumber_UILabel;
    public UILabel FromItem_RemainNumber_UILabel;
    public UISprite FromItem_RemainIcon_UISprite;
    public UILabel FromItem_RemainNumber2_UILabel;
    public UISprite FromItem_RemainIcon2_UISprite;
    public UILabel FromItemRemainLabel_UILabel;
    public UILabel FromItemRemainLabel2_UILabel;
    public UIButton ExchangeButton_UIButton;
    public UIButton TipsButton_UIButton;
    public GameObject FromItem;
    public GameObject FromItem_2;
    public UILabel FromItem_TipLabel_UILabel;
    public UIInput Input_UIInput;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        tab_content = root.FindGameObject("Anchor/tab_content");
        PageTurnView = root.FindGameObject("Anchor/PageTurnView");
        ExpectItemTips_UILabel = root.FindScript<UILabel>("Anchor/ExpectItemTips");
        From_ItemIcon_UISprite = root.FindScript<UISprite>("Anchor/NeedPart/From_ItemIcon");
        From_ItemNumber_UILabel = root.FindScript<UILabel>("Anchor/NeedPart/From_ItemIcon/From_ItemNumber");
        To_ItemIcon_UISprite = root.FindScript<UISprite>("Anchor/NeedPart/To_ItemIcon");
        To_ItemNumber_UILabel = root.FindScript<UILabel>("Anchor/NeedPart/To_ItemIcon/To_ItemNumber");
        FromItem = root.FindGameObject("Anchor/FromItem");
        FromItem_2 = root.FindGameObject("Anchor/FromItem_2");
        FromItem_RemainNumber_UILabel = root.FindScript<UILabel>("Anchor/FromItem/FromItem_RemainNumber");
        FromItem_RemainIcon_UISprite = root.FindScript<UISprite>("Anchor/FromItem/FromItem_RemainIcon");
        FromItem_RemainNumber2_UILabel = root.FindScript<UILabel>("Anchor/FromItem_2/FromItem_RemainNumber2");
        FromItem_RemainIcon2_UISprite = root.FindScript<UISprite>("Anchor/FromItem_2/FromItem_RemainIcon2");
        FromItemRemainLabel_UILabel = root.FindScript<UILabel>("Anchor/FromItem/FromItemRemainLabel");
        FromItemRemainLabel2_UILabel = root.FindScript<UILabel>("Anchor/FromItem_2/FromItemRemainLabel2");
        ExchangeButton_UIButton = root.FindScript<UIButton>("Anchor/ExchangeButton");
        TipsButton_UIButton = root.FindScript<UIButton>("Anchor/TipsBtn");
        FromItem_TipLabel_UILabel = root.FindScript<UILabel>("Anchor/FromItem/FromItem_TipLabel");
        Input_UIInput = root.FindScript<UIInput>("Anchor/PageTurnView/nameMenu/inputLabel");

    }
    #endregion
}
