// **********************************************************************
// Copyright (c) 2016 Baoyugame. All rights reserved.
// Author : Fish
// Created : 12/02/2016 14:34:05
// Desc	: Auto generated by MarsZ. update this if need.
// **********************************************************************

using UnityEngine;

/// <summary>
/// This is the proxy class for module FullServiceAnnouncement, use this to show or hide this module.
/// @Fish in 12/02/2016 14:34:05
/// </summary>
public class ProxyFullServiceAnnouncement
{
    public static void InitListener(){
        FullServiceAnnouncementModel.Instance.updateAnnouncement += OpenView;
    }

    public static void RemoveListerer(){
        FullServiceAnnouncementModel.Instance.updateAnnouncement -= OpenView;
    }

    private static void OpenView(){
        if (ProxyMainUI.CheckMainViewOpen) {
            //Sometimes you may need to do something before opening controller,such as checking function open or not、getting data first etc. 
            var tController = UIModuleManager.Instance.OpenFunModule<FullServiceAnnouncementController>(FullServiceAnnouncementView.NAME, UILayerType.FloatTip, false);
            tController.ShowAnnouncementCallback ();
        } else {
            Close ();
        }
    }
     
    private static void Open()
    {
        
    }

    public static void Hide()
    {
        UIModuleManager.Instance.HideModule(FullServiceAnnouncementView.NAME);	
    }

    public static void Close()
    {
        UIModuleManager.Instance.CloseModule(FullServiceAnnouncementView.NAME);
    }
}