// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  FlowerEffItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IFlowerEffItemController
{
     UniRx.IObservable<Unit> OnBg_UIButtonClick{get;}

}

public partial class FlowerEffItemController:MonolessViewController<FlowerEffItem>, IFlowerEffItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        Bg_UIButtonEvt = View.Bg_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        Bg_UIButtonEvt = Bg_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> Bg_UIButtonEvt;
    public UniRx.IObservable<Unit> OnBg_UIButtonClick{
        get {return Bg_UIButtonEvt;}
    }


}
