// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuildBoxEventsItem : BaseView
{
    public const string NAME ="GuildBoxEventsItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel label_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        label_UILabel = root.FindScript<UILabel>("label");

    }
    #endregion
}
