// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuildWelfareView : BaseView
{
    public const string NAME ="GuildWelfareView";

    #region Element Bindings

    /// bind gameobject
    public UIButton explainBtn_UIButton;
    public UIGrid UIGrid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        explainBtn_UIButton = root.FindScript<UIButton>("Top/explainBtn");
        UIGrid_UIGrid = root.FindScript<UIGrid>("Bottom/GuildPanel/UIGrid");

    }
    #endregion
}
