// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class QuartzView : BaseView
{
    public const string NAME ="QuartzView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UIGrid TabBtn_UIGrid;
    public GameObject ExtendPanel;
    public GameObject ForgeGroup;
    public GameObject StrengthGroup;
    public GameObject InfoGroup;
    public GameObject ScrollView_UIScrollView;
    public GameObject ScrollView;
    public UIButton ShowTypeBtn_UIButton;
    public UILabel TypeLabel_UILabel;
    public Transform ListBtnGroup_Transform;
    public UIPanel ListBtnGroup_UIPanel;
    public GameObject PartnerList_GameObject;
    public UI_Contorl_ScrollFlow UI_PartnerScrollView;
    public UIScrollView TiledScrollView_UIScrollView;
    public UIPageGrid TiledIconGrid_UIPageGrid;
    public UIButton PullbackBtn_UIButton;
    public UIPanel BtnGroup_UIPanel;
    public UIButton TypeBtn_UIButton;
    public UILabel TypeLb_UILabel;
    public UIButton CloseExtendBtn_UIButton;
    public UIButton PullBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseMainWindow/CloseBtn");
        TabBtn_UIGrid = root.FindScript<UIGrid>("Content/TabBtn");
        ExtendPanel = root.FindGameObject("Content/ExtendPanel");
        ForgeGroup = root.FindGameObject("Content/ForgeGroup");
        StrengthGroup = root.FindGameObject("Content/StrengthGroup");
        InfoGroup = root.FindGameObject("Content/InfoGroup");
        ScrollView_UIScrollView = root.FindGameObject("Content/ScrollView/ScrollView");
        ScrollView = root.FindGameObject("Content/ScrollView");
        ShowTypeBtn_UIButton = root.FindScript<UIButton>("Content/ShowTypeBtn");
        TypeLabel_UILabel = root.FindScript<UILabel>("Content/ShowTypeBtn/TypeLabel");
        ListBtnGroup_Transform = root.FindTrans("Content/ShowTypeBtn/ListBtnGroup");
        ListBtnGroup_UIPanel = root.FindScript<UIPanel>("Content/ShowTypeBtn/ListBtnGroup");
        PartnerList_GameObject = root.FindGameObject("Content/ScrollView/ScrollView/PartnerScrollView/PartnerList");
        UI_PartnerScrollView = root.FindScript<UI_Contorl_ScrollFlow>("Content/ScrollView/ScrollView/PartnerScrollView");
        TiledScrollView_UIScrollView = root.FindScript<UIScrollView>("Content/ExtendPanel/TiledScrollView");
        TiledIconGrid_UIPageGrid = root.FindScript<UIPageGrid>("Content/ExtendPanel/TiledScrollView/TiledIconGrid");
        PullbackBtn_UIButton = root.FindScript<UIButton>("Content/ExtendPanel/PullbackBtn");
        BtnGroup_UIPanel = root.FindScript<UIPanel>("Content/ExtendPanel/BtnGroup");
        TypeBtn_UIButton = root.FindScript<UIButton>("Content/ExtendPanel/TypeBtn");
        TypeLb_UILabel = root.FindScript<UILabel>("Content/ExtendPanel/TypeBtn/TypeLabel");
        CloseExtendBtn_UIButton = root.FindScript<UIButton>("Content/ExtendPanel/CloseExtendBtn");
        PullBtn_UIButton = root.FindScript<UIButton>("Content/PullBtn");

    }
    #endregion
}
