//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleSkillSelectView.
/// </summary>
public partial class BattleSkillSelectView : BaseView
{
    public const string NAME ="BattleSkillSelectView";
    public UISprite BGSprite_UISprite;
    public UIButton CloseBtn_UIButton;
    public UITable Table;
    public UIWidget AnchorContainer;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
        BGSprite_UISprite = root.Find("AnchorContainer/BGSprite").GetComponent<UISprite>();
        CloseBtn_UIButton = root.Find("AnchorContainer/CloseBtn").GetComponent<UIButton>();
        Table = root.Find("AnchorContainer/TableContainer/Table").GetComponent<UITable>();
        AnchorContainer = root.Find("AnchorContainer").GetComponent<UIWidget>();
    }
}
