// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EquipmentAttrContentController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IEquipmentAttrContentController
{

}

public partial class BaseEquipmentAttrContentController:MonolessViewController<EquipmentAttrContent>, IEquipmentAttrContentController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
