// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  ResetAttrItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IResetAttrItemController
{

}

public partial class ResetAttrItemController:MonolessViewController<ResetAttrItem>, IResetAttrItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
