// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  FacePanelViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class FacePanelViewController:MonolessViewController<FacePanelView>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        SearchBtn_UIButtonEvt = View.searchBtn_UIButton.AsObservable();
        CloseBtn_UIButtonEvt = View.closeBtn_UIButton.AsObservable();
    }

    protected override void ClearReactiveEvents(){
        SearchBtn_UIButtonEvt = SearchBtn_UIButtonEvt.CloseOnceNull();
        CloseBtn_UIButtonEvt = CloseBtn_UIButtonEvt.CloseOnceNull();
    }

    private Subject<Unit> SearchBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnSearchBtn_UIButtonClick { get { return SearchBtn_UIButtonEvt; } }
    private Subject<Unit> CloseBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick { get { return CloseBtn_UIButtonEvt; } }

}
