// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewUpGradeView : BaseView
{
    public const string NAME ="CrewUpGradeView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public GameObject CrewIcon;
    public UISlider Slider_UISlider;
    public UILabel LvLabel_UILabel;
    public UILabel ExpLabel_UILabel;
    public UILabel DescLabel_UILabel;
    public UIGrid PropsGrid_UIGrid;
    public UIButton UpGradeBtn_UIButton;
    public UIButton UseAllBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseWindow/CloseBtn");
        CrewIcon = root.FindGameObject("MainContent/CrewIcon");
        Slider_UISlider = root.FindScript<UISlider>("MainContent/Slider");
        LvLabel_UILabel = root.FindScript<UILabel>("MainContent/LvLabel");
        ExpLabel_UILabel = root.FindScript<UILabel>("MainContent/ExpLabel");
        DescLabel_UILabel = root.FindScript<UILabel>("MainContent/DescLabel");
        PropsGrid_UIGrid = root.FindScript<UIGrid>("MainContent/PropsGrid");
        UpGradeBtn_UIButton = root.FindScript<UIButton>("MainContent/UpGradeBtn");
        UseAllBtn_UIButton = root.FindScript<UIButton>("MainContent/UseAllBtn");

    }
    #endregion
}
