// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UniRx;
using UnityEngine;



public partial interface IPropsCompositeView {
         IObservable<Unit> OnCloseBtn_UIButtonClick{get;}
     IObservable<Unit> OnComposeBtn_UIButtonClick{get;}
     IObservable<Unit> OnComposeTipBtn_UIButtonClick{get;}
     IObservable<Unit> OnDecomposeBtn_UIButtonClick{get;}
     IObservable<Unit> OnAnnotationBtn_UIButtonClick{get;}

    
}

public sealed partial class PropsCompositeView :
    BaseView,IPropsCompositeView
{
    public const string NAME ="PropsCompositeView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UISprite TitleNameSprite_UISprite;
    public GameObject WinTabGroup;
    public GameObject outcome;
    public UILabel composeRateLbl_UILabel;
    public GameObject ItemsPos;
    public GameObject materialItem;
    public GameObject ComposePageTurn;
    public GameObject GenericCheckBox;
    public UILabel ConsumeContent_UILabel;
    public UILabel ConsumeTitle_UILabel;
    public UIButton ComposeBtn_UIButton;
    public GameObject CompositeContent;
    public UILabel btnLabel_UILabel;
    public UIButton ComposeTipBtn_UIButton;
    public GameObject DecompositeContent;
    public UIButton DecomposeBtn_UIButton;
    public GameObject DecomposeItem;
    public GameObject AcquisitionItem;
    public UILabel DecConsumeContent_UILabel;
    public UILabel DecConsume_UILabel;
    public GameObject AcquisitionPos;
    public GameObject DecomposePageTurn;
    public GameObject DecTabbtnPos;
    public UIButton AnnotationBtn_UIButton;
    public UILabel titleLabel_UILabel;
    public UISprite TitleSprite_UISprite;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseTabWindow/CloseBtn");
        TitleNameSprite_UISprite = root.FindScript<UISprite>("BaseTabWindow/TitleNameSprite");
        WinTabGroup = root.FindGameObject("BaseTabWindow/WinTabGroup");
        outcome = root.FindGameObject("CompositeContent/compose/outcome");
        composeRateLbl_UILabel = root.FindScript<UILabel>("CompositeContent/compose/arrow/composeRateLbl");
        ItemsPos = root.FindGameObject("ItemsPos");
        materialItem = root.FindGameObject("CompositeContent/compose/materialItem");
        ComposePageTurn = root.FindGameObject("CompositeContent/ComposePageTurn");
        GenericCheckBox = root.FindGameObject("CompositeContent/GenericCheckBox");
        ConsumeContent_UILabel = root.FindScript<UILabel>("CompositeContent/ConsumeContent");
        ConsumeTitle_UILabel = root.FindScript<UILabel>("CompositeContent/ConsumeTitle");
        ComposeBtn_UIButton = root.FindScript<UIButton>("CompositeContent/ComposeBtn");
        CompositeContent = root.FindGameObject("CompositeContent");
        btnLabel_UILabel = root.FindScript<UILabel>("CompositeContent/ComposeBtn/btnLabel");
        ComposeTipBtn_UIButton = root.FindScript<UIButton>("CompositeContent/ComposeTipBtn");
        DecompositeContent = root.FindGameObject("DecompositeContent");
        DecomposeBtn_UIButton = root.FindScript<UIButton>("DecompositeContent/Decompose/DecomposeBtn");
        DecomposeItem = root.FindGameObject("DecompositeContent/Decompose/DecomposeItem");
        AcquisitionItem = root.FindGameObject("DecompositeContent/Decompose/AcquisitionItem");
        DecConsumeContent_UILabel = root.FindScript<UILabel>("DecompositeContent/Decompose/DecConsumeContent");
        AcquisitionPos = root.FindGameObject("DecompositeContent/Decompose/AcquisitionContent/AcquisitionPos");
        DecomposePageTurn = root.FindGameObject("DecompositeContent/Decompose/DecomposePageTurn");
        DecTabbtnPos = root.FindGameObject("DecompositeContent/DecTabbtnPos");
        AnnotationBtn_UIButton = root.FindScript<UIButton>("DecompositeContent/AnnotationBtn");
        titleLabel_UILabel = root.FindScript<UILabel>("BaseTabWindow/TitleBg/titleLabel");
        TitleSprite_UISprite = root.FindScript<UISprite>("BaseTabWindow/TitleBg/TitleSprite");
        DecConsume_UILabel = root.FindScript<UILabel>("DecompositeContent/Decompose/DecConsumeLabel");
    }
    #endregion

    #region Event
    protected override void InitReactiveEvents(){
    CloseBtn_UIButtonEvt = CloseBtn_UIButton.AsObservable();
    ComposeBtn_UIButtonEvt = ComposeBtn_UIButton.AsObservable();
    ComposeTipBtn_UIButtonEvt = ComposeTipBtn_UIButton.AsObservable();
    DecomposeBtn_UIButtonEvt = DecomposeBtn_UIButton.AsObservable();
    AnnotationBtn_UIButtonEvt = AnnotationBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        CloseBtn_UIButtonEvt = CloseBtn_UIButtonEvt.CloseOnceNull();
        ComposeBtn_UIButtonEvt = ComposeBtn_UIButtonEvt.CloseOnceNull();
        ComposeTipBtn_UIButtonEvt = ComposeTipBtn_UIButtonEvt.CloseOnceNull();
        DecomposeBtn_UIButtonEvt = DecomposeBtn_UIButtonEvt.CloseOnceNull();
        AnnotationBtn_UIButtonEvt = AnnotationBtn_UIButtonEvt.CloseOnceNull();

    }

        private Subject<Unit> CloseBtn_UIButtonEvt;
    public IObservable<Unit> OnCloseBtn_UIButtonClick{
        get {return CloseBtn_UIButtonEvt;}
    }

    private Subject<Unit> ComposeBtn_UIButtonEvt;
    public IObservable<Unit> OnComposeBtn_UIButtonClick{
        get {return ComposeBtn_UIButtonEvt;}
    }

    private Subject<Unit> ComposeTipBtn_UIButtonEvt;
    public IObservable<Unit> OnComposeTipBtn_UIButtonClick{
        get {return ComposeTipBtn_UIButtonEvt;}
    }

    private Subject<Unit> DecomposeBtn_UIButtonEvt;
    public IObservable<Unit> OnDecomposeBtn_UIButtonClick{
        get {return DecomposeBtn_UIButtonEvt;}
    }

    private Subject<Unit> AnnotationBtn_UIButtonEvt;
    public IObservable<Unit> OnAnnotationBtn_UIButtonClick{
        get {return AnnotationBtn_UIButtonEvt;}
    }


    
    
    #endregion
}
