// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewObtainPanel : BaseView
{
    public const string NAME ="CrewObtainPanel";

    #region Element Bindings

    /// bind gameobject
    public UILabel PowerLabel_UILabel;
    public UILabel SpiritLabel_UILabel;
    public UILabel CharacterLabel_UILabel;
    public UILabel ConstitutionLabel_UILabel;
    public UILabel MPLabel_UILabel;
    public UILabel HPLabel_UILabel;
    public UILabel PhysicsAttackLabel_UILabel;
    public UILabel MagicAttackLabel_UILabel;
    public UILabel PhysicsPierceLabel_UILabel;
    public UILabel PhysicsCritLabel_UILabel;
    public UILabel TreatmentLabel_UILabel;
    public UILabel SpeedLabel_UILabel;
    public UILabel DefenseLabel_UILabel;
    public UILabel MagicDefLabel_UILabel;
    public UILabel MagicTreatment_UILabel;
    public UILabel MagicCrit_UILabel;
    public UILabel AbNoramLabel_UILabel;
    public UITexture SkillIcon_1_UISprite;
    public UITexture SkillIcon_2_UISprite;
    public UITexture SkillIcon_3_UISprite;
    public UITexture SkillIcon_4_UISprite;
    public UIButton SkillIcon_1_UIButton;
    public UIButton SkillIcon_2_UIButton;
    public UIButton SkillIcon_3_UIButton;
    public UIButton SkillIcon_4_UIButton;
    public UIButton OneBuy_UIButton;
    public UILabel NameLabel_UILabel;
    public GameObject BodyTexture_UITexture;
    public UIButton CloseBtn_UIButton;
    public GameObject ShowDataBg;
    public GameObject BodyGameobject;
    public UIGrid ChipGrid_UIGrid;
    public GameObject Chip_Gameobjec;
    public Transform RewdIcon_Transrom;
    public GameObject BG_Show;
    public GameObject BG_Show_2;
    public UISprite PloygonMesh_UISprite;
    public UILabel DesLabel;
    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        PowerLabel_UILabel = root.FindScript<UILabel>("DataBg/BasicsTitle/BG/DataLabel/PowerLabel");
        SpiritLabel_UILabel = root.FindScript<UILabel>("DataBg/BasicsTitle/BG/DataLabel/SpiritLabel");
        CharacterLabel_UILabel = root.FindScript<UILabel>("DataBg/BasicsTitle/BG/DataLabel/CharacterLabel");
        ConstitutionLabel_UILabel = root.FindScript<UILabel>("DataBg/BasicsTitle/BG/DataLabel/ConstitutionLabel");
        MPLabel_UILabel = root.FindScript<UILabel>("DataBg/BasicsTitle/BG/DataLabel/MPLabel");
        HPLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/HPLabel");
        PhysicsAttackLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/PhysicsAttackLabel");
        MagicAttackLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/MagicAttackLabel");
        PhysicsPierceLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/PhysicsPierceLabel");
        PhysicsCritLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/PhysicsCritLabel");
        TreatmentLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/TreatmentLabel");
        SpeedLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/SpeedLabel");
        DefenseLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/DefenseLabel");
        MagicDefLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/MagicDefLabel");
        MagicTreatment_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/MagicTreatment");
        MagicCrit_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/MagicCrit");
        AbNoramLabel_UILabel = root.FindScript<UILabel>("DataBg/BattleTitle/BG/DataLabel/AbNoramLabel");
        SkillIcon_1_UISprite = root.FindScript<UITexture>("DataBg/SkillTitle/BG/Skill_1/SkillIcon_1");
        SkillIcon_2_UISprite = root.FindScript<UITexture>("DataBg/SkillTitle/BG/Skill_2/SkillIcon_2");
        SkillIcon_3_UISprite = root.FindScript<UITexture>("DataBg/SkillTitle/BG/Skill_3/SkillIcon_3");
        SkillIcon_4_UISprite = root.FindScript<UITexture>("DataBg/SkillTitle/BG/Skill_4/SkillIcon_4");
        SkillIcon_1_UIButton = root.FindScript<UIButton>("DataBg/SkillTitle/BG/Skill_1/SkillIcon_1");
        SkillIcon_2_UIButton = root.FindScript<UIButton>("DataBg/SkillTitle/BG/Skill_2/SkillIcon_2");
        SkillIcon_3_UIButton = root.FindScript<UIButton>("DataBg/SkillTitle/BG/Skill_3/SkillIcon_3");
        SkillIcon_4_UIButton = root.FindScript<UIButton>("DataBg/SkillTitle/BG/Skill_4/SkillIcon_4");
        OneBuy_UIButton = root.FindScript<UIButton>("OneBuy");
        NameLabel_UILabel = root.FindScript<UILabel>("BodyUI/titleBG/NameLabel");
        BodyTexture_UITexture = root.FindGameObject("BodyUI/BodyTexture");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        ShowDataBg = root.FindGameObject("DataBg");
        BodyGameobject = root.FindGameObject("BodyUI");
        ChipGrid_UIGrid = root.FindScript<UIGrid>("ChipGrid");
        Chip_Gameobjec = root.FindGameObject("ChipGrid/Chip");
        RewdIcon_Transrom = root.FindScript<Transform>("Icon");
        BG_Show = root.FindGameObject("BG_0");
        BG_Show_2 = root.FindGameObject("BG_1");
        PloygonMesh_UISprite = root.FindScript<UISprite>("DataBg/BasicsTitle/PloygonMesh");
        DesLabel = root.FindScript<UILabel>("DesLabel");
    }
    #endregion
}
