// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SpecialCopyMissionPanel : BaseView
{
    public const string NAME ="SpecialCopyMissionPanel";

    #region Element Bindings

    /// bind gameobject
    public UIButton OnClose_UIButton;
    public UIButton GoToNpc_UIButton;
    public GameObject Stars;
    public UILabel LevelLabel_UILabel;
    public UISprite headSprite_UISprite;
    public UILabel NameLabel_UILabel;
    public UILabel TitleLabel_UILabel;
    public UILabel ContentLabel_UILabel;
    public UILabel GoToLabel_UILabel;
    public Transform TweenBG_Transform;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        OnClose_UIButton = root.FindScript<UIButton>("BG/OnClose");
        GoToNpc_UIButton = root.FindScript<UIButton>("BG/GoToNpc");
        Stars = root.FindGameObject("BG/StarsBG/Stars");
        LevelLabel_UILabel = root.FindScript<UILabel>("BG/NeetLevelBG/LevelLabel");
        headSprite_UISprite = root.FindScript<UISprite>("BG/BossIma/headSprite");
        TitleLabel_UILabel = root.FindScript<UILabel>("BG/BG_2/TitleBG/TitleLabel");
        ContentLabel_UILabel = root.FindScript<UILabel>("BG/BG_2/TitleBG/ContentLabel");
        TweenBG_Transform = root.FindScript<Transform>("BG");
        GoToLabel_UILabel = root.FindScript<UILabel>("BG/GoToNpc/Label");
    }
    #endregion
}
