// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewIconItem : BaseView
{
    public const string NAME ="CrewIconItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite IconBg_UISprite;
    public UISprite Icon_UISprite;
    public UILabel NameLb_UILabel;
    public UISprite Mark_UISprite;
    public UILabel LvLb_UILabel;
    public UIButton CrewIconItem_UIButton;
    public Transform Anchor_Transform;
    public UISprite State_UISprite;
    public UISprite Select_UISprite;
    public UISprite BackGround_UISprite;
    public UISprite OtherSprite_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        IconBg_UISprite = root.FindScript<UISprite>("IconBg");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        NameLb_UILabel = root.FindScript<UILabel>("NameLb");
        Mark_UISprite = root.FindScript<UISprite>("Mark");
        LvLb_UILabel = root.FindScript<UILabel>("LvLb");
        CrewIconItem_UIButton = root.FindScript<UIButton>("");
        Anchor_Transform = root.FindTrans("Anchor");
        State_UISprite = root.FindScript<UISprite>("State");
        Select_UISprite = root.FindScript<UISprite>("Select");
        BackGround_UISprite = root.FindScript<UISprite>("BackGround");
        OtherSprite_UISprite = root.FindScript<UISprite>("OtherSprite");

    }
    #endregion
}
