// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewItemCell : BaseView
{
    public const string NAME ="CrewItemCell";

    #region Element Bindings

    /// bind gameobject
    public UISprite CrewIcon_UISprite;
    public GameObject bg_select;
    public GameObject bg_normal;
    public UISprite FactionSprite_UISprite;
    public UISprite MagicSprite_UISprite;
    public UILabel LevelLabel_UILabel;
    public UISprite Rare_UISprite;
    public UISprite Type_UISprite;
    public GameObject Lv;
    public UIButton CrewItemCell_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CrewIcon_UISprite = root.FindScript<UISprite>("CrewIcon");
        bg_select = root.FindGameObject("bg_select");
        bg_normal = root.FindGameObject("bg_normal");
        FactionSprite_UISprite = root.FindScript<UISprite>("Shuxing/FactionSprite");
        MagicSprite_UISprite = root.FindScript<UISprite>("Shuxing/MagicSprite");
        LevelLabel_UILabel = root.FindScript<UILabel>("Lv/LevelLabel");
        Rare_UISprite = root.FindScript<UISprite>("Rare");
        Type_UISprite = root.FindScript<UISprite>("Type");
        Lv = root.FindGameObject("Lv");
        CrewItemCell_UIButton = root.FindScript<UIButton>("");

    }
    #endregion
}
