// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GuildBoxEventsItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGuildBoxEventsItemController
{

}

public partial class GuildBoxEventsItemController:MonolessViewController<GuildBoxEventsItem>, IGuildBoxEventsItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
