// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GuildWelfareViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGuildWelfareViewController
{
     UniRx.IObservable<Unit> OnexplainBtn_UIButtonClick{get;}

}

public partial class GuildWelfareViewController:MonolessViewController<GuildWelfareView>, IGuildWelfareViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        explainBtn_UIButtonEvt = View.explainBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        explainBtn_UIButtonEvt = explainBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> explainBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnexplainBtn_UIButtonClick{
        get {return explainBtn_UIButtonEvt;}
    }
    

}
