// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GMCodeViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class GMCodeViewController:MonolessViewController<GMCodeView>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        btnSend_UIButtonEvt = View.btnSend_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        btnSend_UIButtonEvt = btnSend_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> btnSend_UIButtonEvt;
    public UniRx.IObservable<Unit> OnbtnSend_UIButtonClick{
        get {return btnSend_UIButtonEvt;}
    }


}
