// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GMCodeItemController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class GMCodeItemController:MonolessViewController<GMCodeItem>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        btnEnter_UIButtonEvt = View.btnEnter_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        btnEnter_UIButtonEvt = btnEnter_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> btnEnter_UIButtonEvt;
    public UniRx.IObservable<Unit> OnbtnEnter_UIButtonClick{
        get {return btnEnter_UIButtonEvt;}
    }


}
