// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using AppDto;
using UniRx;




public partial interface IItemUseTipsView{
         UniRx.IObservable<Unit> OnOptBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{get;}

    
}

public sealed partial class ItemUseTipsView :
    BaseView,IItemUseTipsView
{
    public const string NAME ="ItemUseTipsView";

    #region Element Bindings

    /// bind gameobject
        private UIButton OptBtn_UIButton;
    private UIButton CloseBtn_UIButton;
    private UILabel TitleLabel_UILabel;
    private UILabel ContentLabel_UILabel;
    private UIGrid itemGrid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
                OptBtn_UIButton = root.FindScript<UIButton>("OptBtn");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        TitleLabel_UILabel = root.FindScript<UILabel>("TitleGroup/TitleLabel");
        ContentLabel_UILabel = root.FindScript<UILabel>("table/ContentLabel");
        itemGrid_UIGrid = root.FindScript<UIGrid>("table/itemGrid");

    }
    #endregion

    #region Event
    protected override void InitReactiveEvents(){
            OptBtn_UIButtonEvt = OptBtn_UIButton.AsObservable();
    CloseBtn_UIButtonEvt = CloseBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
                OptBtn_UIButtonEvt = OptBtn_UIButtonEvt.CloseOnceNull();
        CloseBtn_UIButtonEvt = CloseBtn_UIButtonEvt.CloseOnceNull();

    }

        private Subject<Unit> OptBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnOptBtn_UIButtonClick{
        get {return OptBtn_UIButtonEvt;}
    }

    private Subject<Unit> CloseBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{
        get {return CloseBtn_UIButtonEvt;}
    }


    
    
    #endregion
}
