//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for UseItemCell.
/// </summary>
public partial class UseItemCell : BaseView
{
	public const string NAME ="UseItemCell";
	public UIButton RomeveBtn;
	public UILabel CountLabel;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		RomeveBtn = root.Find("RomeveBtn").GetComponent<UIButton>();
		CountLabel = root.Find("CountLabel").GetComponent<UILabel>();
	}
}
