// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class GrooveView : BaseView
{
    public const string NAME = "GrooveView";

    #region Element Bindings

    /// bind gameobject
    public UIWidget Type_2_UIWidget;
    public UIWidget Type_3_UIWidget;
    public UIWidget Type_4_UIWidget;
    public UIWidget Type_5_UIWidget;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Type_2_UIWidget = root.FindScript<UIWidget>("Type_2");
        Type_3_UIWidget = root.FindScript<UIWidget>("Type_3");
        Type_4_UIWidget = root.FindScript<UIWidget>("Type_4");
        Type_5_UIWidget = root.FindScript<UIWidget>("Type_5");

    }
    #endregion
}
