// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BattleCrewItem : BaseView
{
    public const string NAME ="BattleCrewItem";

    #region Element Bindings

    /// bind gameobject
    public UIButton ItemBtn_UIButton;
    public UISprite Icon_UISprite;
    public UISprite IconBG_UISprite;
    public UILabel LvLb_UILabel;
    public UISprite AttriSpr_UISprite;
    public UISprite QuartzSpr_UISprite;
    public UILabel NameLb_UILabel;
    public UILabel PowerLb_UILabel;
    public UISprite SelectSpr_UISprite;
    public UISprite StateSprite_UISprite;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ItemBtn_UIButton = root.FindScript<UIButton>("ItemBtn");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        IconBG_UISprite = root.FindScript<UISprite>("Icon/IconBG");
        LvLb_UILabel = root.FindScript<UILabel>("Icon/LvLb");
        AttriSpr_UISprite = root.FindScript<UISprite>("AttriSpr");
        QuartzSpr_UISprite = root.FindScript<UISprite>("QuartzSpr");
        NameLb_UILabel = root.FindScript<UILabel>("NameLb");
        PowerLb_UILabel = root.FindScript<UILabel>("PowerLb");
        SelectSpr_UISprite = root.FindScript<UISprite>("SelectSpr");
        StateSprite_UISprite = root.FindScript<UISprite>("StateSprite");
    }
    #endregion
}
