//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GMView.
/// </summary>
public partial class NewGMView : BaseView
{
	public const string NAME = "NewGMView";
	public UIButton CleanGuidePlayBtn_UIButton;
	public UIButton GuidePlayBtn_UIButton;
	public UIButton PlotPlayerBtn_UIButton;
	public UIInput PlotPlayerInput_UIInput;
	public UIButton GMExpandCloseBtn_UIButton;
	public UIButton RecordCloseBtn_UIButton;
	public UILabel RepeatTipLabel_UILabel;
	public UIButton CleanRecordBtn_UIButton;
	public UIButton RepeatBtn_UIButton;
	public GameObject RecordGrid;
	public BoxCollider RecordGrid_BoxCollider;
	public UIButton GMExpandOpenBtn_UIButton;
	public UIButton RecordOpenBtn_UIButton;
	public UIButton MainCloseBtn_UIButton;
	public UILabel TipLabel_UILabel;
	public UIButton MarkBtn_UIButton;
	public UIGrid NextBtnsGrid_UIGrid;
	public UIScrollView NextBtnsScrollView_UIScrollView;
	public UIScrollView MainBtnsScrollView_UIScrollView;
	public UILabel InputLabel_UILabel;
	public UIInput InputSprite_UIInput;
	public UIPanel Record_UIPanel;
	public UIPanel GMExpand_UIPanel;
	public Transform GMPosition_Transform;
	public GameObject MainBtnsGrid;
	public Transform NextBtnsGrid_Transform;
	public UIScrollView RecordScrollView_UIScrollView;
	public BoxCollider NextBtnsGrid_BoxCollider;
	public BoxCollider MainBtnsGrid_BoxCollider;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		CleanGuidePlayBtn_UIButton = root.Find("GMPosition/GMExpand/ExpandContent/PlotPlay/CleanGuidePlayBtn").GetComponent<UIButton>();
		GuidePlayBtn_UIButton = root.Find("GMPosition/GMExpand/ExpandContent/PlotPlay/GuidePlayBtn").GetComponent<UIButton>();
		PlotPlayerBtn_UIButton = root.Find("GMPosition/GMExpand/ExpandContent/PlotPlay/PlotPlayerBtn").GetComponent<UIButton>();
		PlotPlayerInput_UIInput = root.Find("GMPosition/GMExpand/ExpandContent/PlotPlay/PlotPlayerInput").GetComponent<UIInput>();
		GMExpandCloseBtn_UIButton = root.Find("GMPosition/GMExpand/GMExpandCloseBtn").GetComponent<UIButton>();
		RecordCloseBtn_UIButton = root.Find("GMPosition/Record/RecordCloseBtn").GetComponent<UIButton>();
		RepeatTipLabel_UILabel = root.Find("GMPosition/Record/RepeatBtn/RepeatTipLabel").GetComponent<UILabel>();
		CleanRecordBtn_UIButton = root.Find("GMPosition/Record/CleanRecordBtn").GetComponent<UIButton>();
		RepeatBtn_UIButton = root.Find("GMPosition/Record/RepeatBtn").GetComponent<UIButton>();
		RecordGrid = root.Find("GMPosition/Record/GameObject/RecordScrollView/RecordGrid").gameObject;
		RecordGrid_BoxCollider = root.Find("GMPosition/Record/GameObject/RecordScrollView/RecordGrid").GetComponent<BoxCollider>();
		GMExpandOpenBtn_UIButton = root.Find("GMPosition/Main/GMExpandOpenBtn").GetComponent<UIButton>();
		RecordOpenBtn_UIButton = root.Find("GMPosition/Main/RecordOpenBtn").GetComponent<UIButton>();
		MainCloseBtn_UIButton = root.Find("GMPosition/Main/MainCloseBtn").GetComponent<UIButton>();
		TipLabel_UILabel = root.Find("GMPosition/Main/Label/TipLabel").GetComponent<UILabel>();
		MarkBtn_UIButton = root.Find("GMPosition/Main/MarkBtn").GetComponent<UIButton>();
		NextBtnsGrid_UIGrid = root.Find("GMPosition/Main/NextBtnsScrollView/NextBtnsGrid").GetComponent<UIGrid>();
		NextBtnsScrollView_UIScrollView = root.Find("GMPosition/Main/NextBtnsScrollView").GetComponent<UIScrollView>();
		MainBtnsScrollView_UIScrollView = root.Find("GMPosition/Main/GameObject/MainBtnsScrollView").GetComponent<UIScrollView>();
		InputLabel_UILabel = root.Find("GMPosition/Main/InputSprite/InputLabel").GetComponent<UILabel>();
		InputSprite_UIInput = root.Find("GMPosition/Main/InputSprite").GetComponent<UIInput>();
		Record_UIPanel = root.Find("GMPosition/Record").GetComponent<UIPanel>();
		GMExpand_UIPanel = root.Find("GMPosition/GMExpand").GetComponent<UIPanel>();
		GMPosition_Transform = root.Find("GMPosition");
		MainBtnsGrid = root.Find("GMPosition/Main/GameObject/MainBtnsScrollView/MainBtnsGrid").gameObject;
		NextBtnsGrid_Transform = root.Find("GMPosition/Main/NextBtnsScrollView/NextBtnsGrid");
		RecordScrollView_UIScrollView = root.Find("GMPosition/Record/GameObject/RecordScrollView").GetComponent<UIScrollView>();
		NextBtnsGrid_BoxCollider = root.Find("GMPosition/Main/NextBtnsScrollView/NextBtnsGrid").GetComponent<BoxCollider>();
		MainBtnsGrid_BoxCollider = root.Find("GMPosition/Main/GameObject/MainBtnsScrollView/MainBtnsGrid").GetComponent<BoxCollider>();
	}
}
