// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RankingInfoCellController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IRankingInfoCellController
{
     UniRx.IObservable<Unit> OnTipsBtn_UIButtonClick{get;}

}

public partial class RankingInfoCellController:MonolessViewController<RankingInfoCell>, IRankingInfoCellController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        TipsBtn_UIButtonEvt = View.TipsBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        TipsBtn_UIButtonEvt = TipsBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> TipsBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTipsBtn_UIButtonClick{
        get {return TipsBtn_UIButtonEvt;}
    }


}
