// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GrooveViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGrooveViewController
{

}

public partial class GrooveViewController:MonolessViewController<GrooveView>, IGrooveViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
