// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ActorPopoModuleView : BaseView
{
    public const string NAME ="ActorPopoModuleView";

    #region Element Bindings

    /// bind gameobject
    public UILabel MsgLabel_UILabel;
    public UIFollowTarget ActorPopoModuleView_UIFollowTarget;
    public UISprite Background_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        MsgLabel_UILabel = root.FindScript<UILabel>("MsgLabel");
        ActorPopoModuleView_UIFollowTarget = root.FindScript<UIFollowTarget>("");
        Background_UISprite = root.FindScript<UISprite>("MsgLabel/Background");

    }
    #endregion
}
