// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class Eq_GoodsChoiceContent : BaseView
{
    public const string NAME ="Eq_GoodsChoiceContent";

    #region Element Bindings

    /// bind gameobject
    public UIScrollView ScrollView_UIScrollView;
    public UIGrid RightContent_UIGrid;
    public GameObject EmptyPanel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("ScrollView");
        RightContent_UIGrid = root.FindScript<UIGrid>("ScrollView/RightContent");
        EmptyPanel = root.FindGameObject("EmptyPanel");

    }
    #endregion
}
