// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class EquipmentChoiceContent : BaseView
{
    public const string NAME ="EquipmentChoiceContent";

    #region Element Bindings

    /// bind gameobject
    public GameObject tabBtn_1;
    public UIGrid EquipmentCellContent_UIGrid;
    public UITable tabBtn_1_UITable;
    public UIScrollView scrollView_UIScrollView;
    public GameObject EmptyPanel;
    public UILabel EmptyLabel_UILabel;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        tabBtn_1 = root.FindGameObject("tabBtn_1");
        EquipmentCellContent_UIGrid = root.FindScript<UIGrid>("Srollview/EquipmentCellContent");
        tabBtn_1_UITable = root.FindScript<UITable>("tabBtn_1");
        scrollView_UIScrollView = root.FindScript<UIScrollView>("Srollview");
        EmptyPanel = root.FindGameObject("EmptyPanel");
        EmptyLabel_UILabel = root.FindScript<UILabel>("EmptyPanel/Label");
    }
    #endregion
}
