// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class EquipmentItemCell : BaseView
{
    public const string NAME ="EquipmentItemCell";

    #region Element Bindings

    /// bind gameobject
    public UISprite Eq_Icon_UISprite;
    public UISprite Eq_grayMask_UISprite;
    public UISprite Quality_Border_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Eq_Icon_UISprite = root.FindScript<UISprite>("Eq_Icon");
        Eq_grayMask_UISprite = root.FindScript<UISprite>("Eq_grayMask");
        Quality_Border_UISprite = root.FindScript<UISprite>("Quality_Border");

    }
    #endregion
}
