// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  ChatSystemItem2Controller.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class ChatSystemItem2Controller:MonolessViewController<ChatSystemItem2>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
