// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RedPointController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IRedPointController
{

}

public partial class RedPointController:MonolessViewController<RedPointView>, IRedPointController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
