//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ModelTitleHUDView.
/// </summary>
public partial class ModelTitleHUDView : BaseView
{
    public const string NAME = "ModelTitleHUDView";
    public UILabelHUD nameLbl;
    public UIFollowTarget follower;

    protected override void InitElementBinding()
    {
        var root = this.gameObject.transform;
        nameLbl = root.Find("nameLbl").GetComponent<UILabelHUD>();
        follower = root.GetComponent<UIFollowTarget>();
    }
}
