//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ModelHeadHUDView.
/// </summary>
public partial class ModelHeadHUDView : BaseView
{
	public const string NAME ="ModelHeadHUDView";
	public UISpriteAnimation runFlagSpriteAnimation;
	public UISpriteAnimation fightFlagSpriteAnimation;
	public UISpriteAnimation teamFlagSpriteAnimation;
	public UISprite missionTypeSprite;
	public UILabel teamCount_UILabel;
	public UISprite teamInfo_UISprite;
	public UISprite escortFlag_UISprite;
	public UIFollowTarget follower;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		runFlagSpriteAnimation = root.Find("runFlag").GetComponent<UISpriteAnimation>();
		fightFlagSpriteAnimation = root.Find("fightFlag").GetComponent<UISpriteAnimation>();
		teamFlagSpriteAnimation = root.Find("teamFlag").GetComponent<UISpriteAnimation>();
		missionTypeSprite = root.Find("missionType").GetComponent<UISprite>();
		teamCount_UILabel = root.Find("teamInfo/teamCount").GetComponent<UILabel>();
		teamInfo_UISprite = root.Find("teamInfo").GetComponent<UISprite>();
		escortFlag_UISprite = root.Find("escortFlag").GetComponent<UISprite>();
	follower = root.GetComponent<UIFollowTarget>();
	}
}
