// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class PropsMagicItem : BaseView
{
    public const string NAME ="PropsMagicItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel TitleLabel_UILabel;
    public UILabel DesLabel_UILabel;
    public UISprite Icon_UISprite;
    public UISprite FactionIcon_UISprite;
    public UILabel proDesLabel_UILabel;
    public UISprite Line_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TitleLabel_UILabel = root.FindScript<UILabel>("TitleLabel");
        DesLabel_UILabel = root.FindScript<UILabel>("DesLabel");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        FactionIcon_UISprite = root.FindScript<UISprite>("FactionIcon");
        proDesLabel_UILabel = root.FindScript<UILabel>("proDesLabel");
        Line_UISprite = root.FindScript<UISprite>("Line");

    }
    #endregion
}
