//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SpeechFlagItem.
/// </summary>
public partial class SpeechFlagItem : BaseView
{
	public const string NAME ="SpeechFlagItem";
	public UILabel tipLbl_UILabel;
	public UISprite stateSprite_UISprite;
	public UISprite volumeSprite_UISprite;
	public UISprite RedUnderLine_UISprite;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		tipLbl_UILabel = root.Find("ContentBg/tipLbl").GetComponent<UILabel>();
		stateSprite_UISprite = root.Find("ContentBg/stateSprite").GetComponent<UISprite>();
		volumeSprite_UISprite = root.Find("ContentBg/stateSprite/volumeSprite").GetComponent<UISprite>();
		RedUnderLine_UISprite = root.Find("ContentBg/tipLbl/RedUnderLine").GetComponent<UISprite>();
	}
}
