// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewSkillTrainingViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ICrewSkillTrainingViewController
{
     UniRx.IObservable<Unit> OnTipButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnbtnSave_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnbtnTraining_UIButtonClick{get;}

}

public partial class CrewSkillTrainingViewController:MonolessViewController<CrewSkillTrainingView>, ICrewSkillTrainingViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        TipButton_UIButtonEvt = View.TipButton_UIButton.AsObservable();
        btnSave_UIButtonEvt = View.btnSave_UIButton.AsObservable();
        btnTraining_UIButtonEvt = View.btnTraining_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        TipButton_UIButtonEvt = TipButton_UIButtonEvt.CloseOnceNull();
        btnSave_UIButtonEvt = btnSave_UIButtonEvt.CloseOnceNull();
        btnTraining_UIButtonEvt = btnTraining_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> TipButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTipButton_UIButtonClick{
        get {return TipButton_UIButtonEvt;}
    }

    private Subject<Unit> btnSave_UIButtonEvt;
    public UniRx.IObservable<Unit> OnbtnSave_UIButtonClick{
        get {return btnSave_UIButtonEvt;}
    }

    private Subject<Unit> btnTraining_UIButtonEvt;
    public UniRx.IObservable<Unit> OnbtnTraining_UIButtonClick{
        get {return btnTraining_UIButtonEvt;}
    }


}
