// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  StrengthContainerViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IStrengthContainerViewController
{
     UniRx.IObservable<Unit> OnDevelopButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnTipButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnStrengthTipBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnStrengthButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnCheckBtn_UIButtonClick{get;}

}

public partial class StrengthContainerViewController:MonolessViewController<StrengthContainerView>, IStrengthContainerViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        DevelopButton_UIButtonEvt = View.DevelopButton_UIButton.AsObservable();
        TipButton_UIButtonEvt = View.TipButton_UIButton.AsObservable();
        StrengthTipBtn_UIButtonEvt = View.StrengthTipBtn_UIButton.AsObservable();
        StrengthButton_UIButtonEvt = View.StrengthButton_UIButton.AsObservable();
        CheckBtn_UIButtonEvt = View.CheckBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        DevelopButton_UIButtonEvt = DevelopButton_UIButtonEvt.CloseOnceNull();
        TipButton_UIButtonEvt = TipButton_UIButtonEvt.CloseOnceNull();
        StrengthTipBtn_UIButtonEvt = StrengthTipBtn_UIButtonEvt.CloseOnceNull();
        StrengthButton_UIButtonEvt = StrengthButton_UIButtonEvt.CloseOnceNull();
        CheckBtn_UIButtonEvt = CheckBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> DevelopButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnDevelopButton_UIButtonClick{
        get {return DevelopButton_UIButtonEvt;}
    }

    private Subject<Unit> TipButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTipButton_UIButtonClick{
        get {return TipButton_UIButtonEvt;}
    }

    private Subject<Unit> StrengthTipBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnStrengthTipBtn_UIButtonClick{
        get {return StrengthTipBtn_UIButtonEvt;}
    }

    private Subject<Unit> StrengthButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnStrengthButton_UIButtonClick{
        get {return StrengthButton_UIButtonEvt;}
    }

    private Subject<Unit> CheckBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCheckBtn_UIButtonClick{
        get {return CheckBtn_UIButtonEvt;}
    }


}
