// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ShopMainView : BaseView
{
    public const string NAME ="ShopMainView";

    #region Element Bindings

    /// bind gameobject
    public GameObject Content;
    public UIButton CloseBtn_UIButton;
    public GameObject tabBtn_1;
    public GameObject tabBtn_2;
    public UISprite PriceIcon_UISprite;
    public UILabel PriceLabel_UILabel;
    public UIButton BuyButton_UIButton;
    public GameObject PageTurnView;
    public UIRecycledList RecycleList;
    public UILabel ShopRemainTime_UILabel;
    public UIButton ResetButton_UIButton;
    public UILabel ShopGoodsRemainCount_UILabel;
    public UILabel OwnerMoney_UILabel;
    public UISprite OwnerMoneyIcon_UISprite;
    public UISprite TitleNameSprite_UISprite;
    public GameObject OwnerMoney;
    public UILabel resetPrice_UILabel;
    public UIScrollView ScrollView_UIScrollView;
    public GameObject ModelDisplayAnchor;
    public UITexture PlayerTexture_UITexture;
    public GameObject BaseWindow;
    public GameObject TabBg;
    public UILabel OwnerMoneyLabel_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Content = root.FindGameObject("Content");
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseWindow/CloseBtn");
        tabBtn_1 = root.FindGameObject("BaseWindow/tabBtn_1");
        tabBtn_2 = root.FindGameObject("BaseWindow/tabBtn_2");
        PriceIcon_UISprite = root.FindScript<UISprite>("Content/TotalPrice/TotalPriceBg/PriceIcon");
        PriceLabel_UILabel = root.FindScript<UILabel>("Content/TotalPrice/TotalPriceBg/PriceLabel");
        BuyButton_UIButton = root.FindScript<UIButton>("Content/BuyButton");
        PageTurnView = root.FindGameObject("Content/PageTurnView");
        RecycleList = root.FindScript<UIRecycledList>("Content/ScrollView/ShopItemContent");
        ShopRemainTime_UILabel = root.FindScript<UILabel>("Content/ShopRemainTime");
        ResetButton_UIButton = root.FindScript<UIButton>("Content/ResetButton");
        ShopGoodsRemainCount_UILabel = root.FindScript<UILabel>("Content/ShopGoodsRemainCount");
        OwnerMoney_UILabel = root.FindScript<UILabel>("Content/OwnerMoney");
        OwnerMoneyIcon_UISprite = root.FindScript<UISprite>("Content/OwnerMoney/OwnerMoneyIcon");
        TitleNameSprite_UISprite = root.FindScript<UISprite>("BaseWindow/TitleBg/TitleNameSprite");
        OwnerMoney = root.FindGameObject("Content/OwnerMoney");
        resetPrice_UILabel = root.FindScript<UILabel>("Content/ResetButton/resetPrice");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("Content/ScrollView");
        ModelDisplayAnchor = root.FindGameObject("Content/ModelDisplayAnchor");
        PlayerTexture_UITexture = root.FindScript<UITexture>("Content/PlayerTexture");
        BaseWindow = root.FindGameObject("BaseWindow");
        TabBg = root.FindGameObject("BaseWindow/TabBg");
        OwnerMoneyLabel_UILabel = root.FindScript<UILabel>("Content/OwnerMoney/OwnerMoneyLabel");

    }
    #endregion
}
