// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class TradeOptionBtn : BaseView
{
    public const string NAME ="TradeOptionBtn";

    #region Element Bindings

    /// bind gameobject
    public UIButton TradeOptionBtn_UIButton;
    public UILabel BtnNameLb_UILabel;
    public UISprite LittleIcon_UISprite;
    public UISprite Arrow_UISprite;
    public GameObject Select;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TradeOptionBtn_UIButton = root.FindScript<UIButton>("");
        BtnNameLb_UILabel = root.FindScript<UILabel>("BtnNameLb");
        LittleIcon_UISprite = root.FindScript<UISprite>("LittleIcon");
        Arrow_UISprite = root.FindScript<UISprite>("Arrow");
        Select = root.FindGameObject("Select");

    }
    #endregion
}
