// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GarandArenaRankItem : BaseView
{
    public const string NAME ="GarandArenaRankItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel Rank_UILabel;
    public UISprite Icon_UISprite;
    public UILabel Name_UILabel;
    public UILabel Profession_UILabel;
    public UILabel Cup_UILabel;
    public UISprite Bg_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Rank_UILabel = root.FindScript<UILabel>("Rank");
        Icon_UISprite = root.FindScript<UISprite>("Rank/Icon");
        Name_UILabel = root.FindScript<UILabel>("Name");
        Profession_UILabel = root.FindScript<UILabel>("Profession");
        Cup_UILabel = root.FindScript<UILabel>("Cup");
        Bg_UISprite = root.FindScript<UISprite>("Bg");

    }
    #endregion
}
