// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GarandArenaMainView : BaseView
{
    public const string NAME ="GarandArenaMainView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UILabel CupNum_UILabel;
    public UILabel IntergralNum_UILabel;
    public UIButton ExchangeBtn_UIButton;
    public UIButton ReportBtn_UIButton;
    public UIButton EmbattleBtn_UIButton;
    public UIGrid RankGrid_UIGrid;
    public UILabel MyRank_UILabel;
    public UISprite MyRankIcon_UISprite;
    public UILabel MyName_UILabel;
    public UILabel MyFaction_UILabel;
    public UILabel MyCup_UILabel;
    public UIGrid RivalGrid_UIGrid;
    public UIButton TipsBtn_UIButton;
    public UILabel LeftlNum_UILabel;
    public UIButton RefreshBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        CupNum_UILabel = root.FindScript<UILabel>("LeftPanel/MyCup/CupNum");
        IntergralNum_UILabel = root.FindScript<UILabel>("LeftPanel/Down/IntergralNum");
        ExchangeBtn_UIButton = root.FindScript<UIButton>("LeftPanel/Down/ExchangeBtn");
        ReportBtn_UIButton = root.FindScript<UIButton>("LeftPanel/Down/ReportBtn");
        EmbattleBtn_UIButton = root.FindScript<UIButton>("LeftPanel/Down/EmbattleBtn");
        RankGrid_UIGrid = root.FindScript<UIGrid>("RightPanel/RankPanel/RankScrollView/RankGrid");
        MyRank_UILabel = root.FindScript<UILabel>("RightPanel/RankPanel/MyRankItem/MyRank");
        MyRankIcon_UISprite = root.FindScript<UISprite>("RightPanel/RankPanel/MyRankItem/MyRank/MyRankIcon");
        MyName_UILabel = root.FindScript<UILabel>("RightPanel/RankPanel/MyRankItem/MyName");
        MyFaction_UILabel = root.FindScript<UILabel>("RightPanel/RankPanel/MyRankItem/MyFaction");
        MyCup_UILabel = root.FindScript<UILabel>("RightPanel/RankPanel/MyRankItem/MyCup");
        RivalGrid_UIGrid = root.FindScript<UIGrid>("RightPanel/RivalPanel/RivalScrollView/RivalGrid");
        TipsBtn_UIButton = root.FindScript<UIButton>("RightPanel/DownPanel/TipsBtn");
        LeftlNum_UILabel = root.FindScript<UILabel>("RightPanel/DownPanel/LeftlNum");
        RefreshBtn_UIButton = root.FindScript<UIButton>("RightPanel/DownPanel/RefreshBtn");

    }
    #endregion
}
