//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class ChatPlayerItem : BaseView
{
    public const string NAME ="ChatPlayerItem";

    #region Element Bindings

    /// bind gameobject
        public GameObject IconBg;
    public UISprite Icon_UISprite;
    public UILabel LvLbl_UILabel;
    public UILabel PlayerNameAndJob_UILabel;
    public UISprite VoiceSprite_UISprite;
    public UISprite VoiceProgress_UISprite;
    public UILabel VoiceTime_UILabel;
    public UISprite ContentBg_Voice_UISprite;
    public UILabel VoiceTranslateLabel_UILabel;
    public EmojiAnimationController ContentLbl_UILabel;
    public UISprite ContentBg_UISprite;
    public UIButton ContentBg_UIButton;
    public UIButton IconBg_UIButton;
    public UIWidget ChatPlayerItemPrefab1_UIWidget;
    public UISprite IconBg_UISprite;
    public UILabel TirmeLbl_UILabel;
    public UITable littleIconTable_UITable;
    public UIEventListener IconBg__UIEventListener;

    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
                IconBg = root.FindGameObject("IconBg");
        Icon_UISprite = root.FindScript<UISprite>("IconBg/Icon");
        LvLbl_UILabel = root.FindScript<UILabel>("IconBg/LvLbl");
        PlayerNameAndJob_UILabel = root.FindScript<UILabel>("PlayerNameAndJob");
        VoiceSprite_UISprite = root.FindScript<UISprite>("VoiceSprite");
        VoiceProgress_UISprite = root.FindScript<UISprite>("VoiceProgress");
        VoiceTime_UILabel = root.FindScript<UILabel>("VoiceProgress/VoiceTime");
        ContentBg_Voice_UISprite = root.FindScript<UISprite>("ContentBg_Voice");
        VoiceTranslateLabel_UILabel = root.FindScript<UILabel>("ContentBg_Voice/VoiceTranslateLabel");
        ContentLbl_UILabel = root.FindScript<EmojiAnimationController>("ContentLbl");
        ContentBg_UISprite = root.FindScript<UISprite>("ContentLbl/ContentBg");
        ContentBg_UIButton = root.FindScript<UIButton>("ContentLbl/ContentBg");
        IconBg_UIButton = root.FindScript<UIButton>("IconBg");
        ChatPlayerItemPrefab1_UIWidget = root.FindScript<UIWidget>("");
        IconBg_UISprite = root.FindScript<UISprite>("IconBg");
        TirmeLbl_UILabel = root.FindScript<UILabel>("TirmeLbl");
        littleIconTable_UITable = root.FindScript<UITable>("littleIconTable");
        IconBg__UIEventListener = root.FindScript<UIEventListener>("IconBg");
    }
    #endregion
}

