// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ChatSettingPanel : BaseView
{
    public const string NAME ="ChatSettingPanel";

    #region Element Bindings

    /// bind gameobject
    public UIGrid ShowChannelSetting_UIGrid;
    public UIGrid AutoPlayerVoiceSetting_UIGrid;
    public UILabel Tips_UILabel;
    public UIButton ShowChannelBtn_UIButton;
    public UIButton AutoPlayerVoiceBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ShowChannelSetting_UIGrid = root.FindScript<UIGrid>("Bg/MiddleBg/ShowChannelSetting");
        AutoPlayerVoiceSetting_UIGrid = root.FindScript<UIGrid>("Bg/MiddleBg/AutoPlayerVoiceSetting");
        Tips_UILabel = root.FindScript<UILabel>("Bg/Tips");
        ShowChannelBtn_UIButton = root.FindScript<UIButton>("Bg/ShowChannelBtn");
        AutoPlayerVoiceBtn_UIButton = root.FindScript<UIButton>("Bg/AutoPlayerVoiceBtn");

    }
    #endregion
}
