// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class RedPoint : BaseView
{
    public const string NAME ="RedPoint";

    #region Element Bindings

    /// bind gameobject
    public UILabel Num_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Num_UILabel = root.FindScript<UILabel>("Num");

    }
    #endregion
}
