// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using Assets.Scripts.MyGameScripts.Module.RoleSkillModule.View;
using System.Collections.Generic;
using UnityEngine;

public sealed partial class RoleSkillTalentView : BaseView
{
    public const string NAME ="RoleSkillTalentView";

    #region Element Bindings

    /// bind gameobject
    public Transform leftContent_Transform;
    public Transform rightContent_Transform;
    public UILabel lblFactionName_UILabel;
    public UILabel lblFactionDesc_UILabel;
    public UIButton btnReset_UIButton;
    public UILabel lblHas_UILabel;
    public UIButton btnAdd_UIButton;
    public Transform Container_UIWidget;
    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        leftContent_Transform = root.FindTrans("leftContent");
        rightContent_Transform = root.FindTrans("rightContent");
        lblFactionName_UILabel = root.FindScript<UILabel>("rightContent/spNameBG/lblName");
        lblFactionDesc_UILabel = root.FindScript<UILabel>("rightContent/lblFactionDesc");
        btnReset_UIButton = root.FindScript<UIButton>("rightContent/btnReset");
        lblHas_UILabel = root.FindScript<UILabel>("rightContent/lblHas");
        btnAdd_UIButton = root.FindScript<UIButton>("rightContent/btnAdd");
        Container_UIWidget = root.FindTrans("leftContent/scrollView/Container");

    }
    #endregion
}
