//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;


/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class RoleSkillTalentGradeView : BaseView
{
    public const string NAME ="RoleSkillTalentGradeView";

    #region Element Bindings

    /// bind gameobject
    public UILabel lblName_UILabel;
    public UILabel lblDesc_UILabel;
    public UILabel lblType_UILabel;
    public UILabel lblPoint_UILabel;
    public UIButton btnUp_UIButton;


    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
        lblName_UILabel = root.FindScript<UILabel>("lblName");
        lblDesc_UILabel = root.FindScript<UILabel>("lblDesc");
        lblType_UILabel = root.FindScript<UILabel>("lblType");
        lblPoint_UILabel = root.FindScript<UILabel>("lblPoint");
        btnUp_UIButton = root.FindScript<UIButton>("btnUp");

    }
    #endregion
}

