// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class EmbebGroupFristShowAttr : BaseView
{
    public const string NAME ="EmbebGroupFristShowAttr";

    #region Element Bindings

    /// bind gameobject
    public UILabel AttrLabel_UILabel;
    public UILabel AttrChangeLabel_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        AttrLabel_UILabel = root.FindScript<UILabel>("AttrLabel");
        AttrChangeLabel_UILabel = root.FindScript<UILabel>("AttrChangeLabel");

    }
    #endregion
}
