// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GoodsTipsTitleViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGoodsTipsTitleViewController
{

}

public partial class GoodsTipsTitleViewController:MonolessViewController<GoodsTipsTitleView>, IGoodsTipsTitleViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
