//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RoleCreateView.
/// </summary>
public partial class RoleCreateView : BaseView
{
	public const string NAME ="RoleCreateView";
	public UIButton StartGameButton_UIButton;
	public UITexture InfoTexture_UITexture;
	public UIButton CloseButton_UIButton;
	public UIInput RoleNameInput_UIInput;
	public UIButton RollNameButton_UIButton;
	public Transform ModelDragregion_UIEventTrigger;
	public UITable RoleGrid_UIGrid;
	public Transform FactionGroup_Transform;
    public GameObject PartnerList_UITable;
	public UILabel FactionDescLbl_UILabel;
	public UISprite Right_UISprite;
	public UISprite Left_UISprite;
	public UITexture Back2D_UITexture;
	//public UITexture Role2D_UITexture;
	public Transform Role2DGroup_Transform;
    public UIScrollView UIScroll;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		StartGameButton_UIButton = root.Find("StartGameButton").GetComponent<UIButton>();
		InfoTexture_UITexture = root.Find("RoleSelectGroup/InfoTexture").GetComponent<UITexture>();
		CloseButton_UIButton = root.Find("CloseButton").GetComponent<UIButton>();
		RoleNameInput_UIInput = root.Find("RoleNameInputGroup/RoleNameInput").GetComponent<UIInput>();
		RollNameButton_UIButton = root.Find("RoleNameInputGroup/RollNameButton").GetComponent<UIButton>();
		ModelDragregion_UIEventTrigger = root.Find("RoleSelectGroup/ModelDragregion");
		RoleGrid_UIGrid = root.Find("RoleGrid").GetComponent<UITable>();
		FactionGroup_Transform = root.Find("FactionGroup");
        // PartnerList_UITable = root.Find("FactionGroup/PartnerList").GetComponent< UITable>();
        PartnerList_UITable = root.Find("FactionGroup/PartnerList").gameObject;
		//Right_UISprite = root.Find("Bottom/Right").GetComponent<UISprite>();
		//Left_UISprite = root.Find("Bottom/Left").GetComponent<UISprite>();
		Back2D_UITexture = root.Find("Role2DGroup/Back2D").GetComponent<UITexture>();
		//Role2D_UITexture = root.Find("Role2DGroup/Role2D").GetComponent<UITexture>();
		Role2DGroup_Transform = root.Find("Role2DGroup");
        UIScroll = root.Find("FactionGroup").GetComponent<UIScrollView>();

    }
}
