// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class GMDtoConnItem : BaseView
{
    public const string NAME ="GMDtoConnItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel lblName_UILabel;
    public UILabel lblTime_UILabel;
    public UILabel lblSize_UILabel;
    public UISprite spSelected_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        lblName_UILabel = root.FindScript<UILabel>("lblName");
        lblTime_UILabel = root.FindScript<UILabel>("lblTime");
        lblSize_UILabel = root.FindScript<UILabel>("lblSize");
        spSelected_UISprite = root.FindScript<UISprite>("spSelected");

    }
    #endregion
}
