// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SearchFriendView : BaseView
{
    public const string NAME ="SearchFriendView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseButton_UIButton;
    public UIInput InputField_UIInput;
    public UILabel Label_UILabel;
    public UIButton CancleInputBtn_UIButton;
    public UIButton SearchBtn_UIButton;
    public UIGrid Grid_UIGrid;
    public UIButton ChangeBatchBtn_UIButton;
    public UIButton MapBtn_UIButton;
    public UIScrollView ScrollView_UIScrollView;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseButton_UIButton = root.FindScript<UIButton>("CloseButton");
        InputField_UIInput = root.FindScript<UIInput>("InputField");
        Label_UILabel = root.FindScript<UILabel>("InputField/Label");
        CancleInputBtn_UIButton = root.FindScript<UIButton>("CancleInputBtn");
        SearchBtn_UIButton = root.FindScript<UIButton>("SearchBtn");
        Grid_UIGrid = root.FindScript<UIGrid>("ScrollView/Grid");
        ChangeBatchBtn_UIButton = root.FindScript<UIButton>("ChangeBatchBtn");
        MapBtn_UIButton = root.FindScript<UIButton>("MapBtn");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("ScrollView");

    }
    #endregion
}
