// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  ActorPopoModuleViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IActorPopoModuleViewController
{

}

public partial class ActorPopoModuleViewController:MonoViewController<ActorPopoModuleView>, IActorPopoModuleViewController
{
    //机器自动生成的事件绑定
    //protected override void InitReactiveEvents(){

    //}

    //protected override void ClearReactiveEvents(){

    //}
}
