//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MonsterHPSlider.
/// </summary>
public partial class MonsterHPSlider : BaseView
{
	public const string NAME ="MonsterHPSlider";
	public UIWidget CntrBUFF_UIWidget;
	public UISprite ReadySprite_UISprite;
	public UISlider HPSlider_UISlider;
	public UISlider CDSlider_UISlider;
	public UIGrid BuffGrid_UIGrid;
	public GameObject CntrBuffIcon;
	public UISprite Front_Sprite_UISprite;
	public UIWidget CntrBuffIcon_UIWidget;
	public UIWidget MonsterHPSlider_UIWidget;
	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		CntrBUFF_UIWidget = root.Find("CntrBUFF").GetComponent<UIWidget>();
		ReadySprite_UISprite = root.Find("ReadySprite").GetComponent<UISprite>();
		HPSlider_UISlider = root.Find("HPSlider").GetComponent<UISlider>();
		CDSlider_UISlider = root.Find("CDSlider").GetComponent<UISlider>();
		BuffGrid_UIGrid = root.Find("CntrBUFF/BuffGrid").GetComponent<UIGrid>();
		CntrBuffIcon = root.Find("CntrBUFF/CntrBuffIcon").gameObject;
		Front_Sprite_UISprite = root.Find("CDSlider/Front_Sprite").GetComponent<UISprite>();
		CntrBuffIcon_UIWidget = root.Find("CntrBUFF/CntrBuffIcon").GetComponent<UIWidget>();
		MonsterHPSlider_UIWidget = root.GetComponent<UIWidget>();
	}
}
