//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class FormationPosItem : BaseView
{
    public const string NAME ="FormationPosItem";

    #region Element Bindings

    /// bind gameobject
        public GameObject ModelAnchor;
    public UILabel posLbl_UILabel;
    public UISprite factionIcon_UISprite;
    public UISprite selected_UISprite;
    public UISprite FormationPosItem_UISprite;
    public UISpriteAnimation CanExchangeEff_UISpriteAnimation;

    public UISprite bottomSprite;

    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
                ModelAnchor = root.FindGameObject("ModelAnchor");
        posLbl_UILabel = root.FindScript<UILabel>("posLbl");
        factionIcon_UISprite = root.FindScript<UISprite>("factionIcon");
        selected_UISprite = root.FindScript<UISprite>("selected");
        FormationPosItem_UISprite = root.FindScript<UISprite>("");
        CanExchangeEff_UISpriteAnimation = root.FindScript<UISpriteAnimation>("CanExchangeEff");

        bottomSprite = root.GetComponent<UISprite>();
    }
    #endregion
}

