//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class FormationDebuffItem : BaseView
{
    public const string NAME ="FormationDebuffItem";

    #region Element Bindings

    /// bind gameobject
        public UILabel NameLable_UILabel;
    public UILabel EffectLable_UILabel;
    public UIDragScrollView FormationDebuffItem_UIDragScrollView;


    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
                NameLable_UILabel = root.FindScript<UILabel>("NameLable");
        EffectLable_UILabel = root.FindScript<UILabel>("EffectLable");
        FormationDebuffItem_UIDragScrollView = root.FindScript<UIDragScrollView>("");

    }
    #endregion
}

