//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleHUDText.
/// </summary>
public partial class BattleHUDText : BaseView
{
	public const string NAME ="BattleHUDText";
	public UISprite statusSprite;
	public GameObject damageInfo;
	public UILabel msgLbl;
	public UILabel damageLbl;
	public UISprite critSprite;
	public GameObject skillInfo;
	public UISprite skillSprite;
	public UISpriteAnimation skillSpriteAnimation;
	public UILabel skillNameLbl;
	public UIFollowTarget followTarget;
	public UITable tableGO_UITable;
	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		tableGO_UITable = gameObject.FindScript<UITable>("damageInfo/tableGO");
		statusSprite = root.Find("damageInfo/tableGO/statusSprite").GetComponent<UISprite>();
		damageInfo = root.Find("damageInfo").gameObject;
		msgLbl = root.Find("msgLbl").GetComponent<UILabel>();
		damageLbl = root.Find("damageInfo/tableGO/damageLbl").GetComponent<UILabel>();
		critSprite = root.Find("damageInfo/critSprite").GetComponent<UISprite>();
		skillInfo = root.Find("skillInfo").gameObject;
		skillSprite = root.Find("skillInfo/skillSprite").GetComponent<UISprite>();
		skillSpriteAnimation = root.Find("skillInfo/skillSprite").GetComponent<UISpriteAnimation>();
		skillNameLbl = root.Find("skillInfo/skillNameLbl").GetComponent<UILabel>();
		
	followTarget = root.GetComponent<UIFollowTarget>();
	}
}
