// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class QuizariumView : BaseView
{
    public const string NAME ="QuizariumView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UILabel TimeLb_UILabel;
    public UILabel TitleLb_UILabel;
    public UIGrid AnswerGrid_UIGrid;
    public UISlider Slider_UISlider;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        TimeLb_UILabel = root.FindScript<UILabel>("TimeLb");
        TitleLb_UILabel = root.FindScript<UILabel>("TitleLb");
        AnswerGrid_UIGrid = root.FindScript<UIGrid>("AnswerGrid");
        Slider_UISlider = root.FindScript<UISlider>("Slider");

    }
    #endregion
}
