// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RoleSkillMagicViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class RoleSkillMagicViewController:MonolessViewController<RoleSkillMagicView>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        btnOrbment_UIButtonEvt = View.btnOrbment_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        btnOrbment_UIButtonEvt = btnOrbment_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> btnOrbment_UIButtonEvt;
    public UniRx.IObservable<Unit> OnbtnOrbment_UIButtonClick{
        get {return btnOrbment_UIButtonEvt;}
    }


}
