// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RoleSkillRangeController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class RoleSkillRangeController:MonolessViewController<RoleSkillRange>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
