// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class PitchView : BaseView
{
    public const string NAME ="PitchView";

    #region Element Bindings

    /// bind gameobject
    public GameObject BuyGroup;
    public GameObject SellGroup;
    public UIButton BuyGroupBtn_UIButton;
    public UIButton SellGroupBtn_UIButton;
    public UILabel CashLb_UILabel;
    public UIButton AddCashBtn_UIButton;
    public UIScrollView BuyScrollView_UIScrollView;
    public UIGrid BuyGoodsGrid_UIGrid;
    public UIButton RefreshBtn_UIButton;
    public UIScrollView OptionScrollView_UIScrollView;
    public UIGrid OptionGrid_UIGrid;
    public UIButton BuyItemBtn_UIButton;
    public UILabel PageLb_UILabel;
    public UIButton NextBtn_UIButton;
    public UIButton LastBtn_UIButton;
    public UIButton SellTipBtn_UIButton;
    public UIScrollView SellItemScrollView_UIScrollView;
    public UIGrid SellItemGrid_UIGrid;
    public UIButton OneKeySellBtn_UIButton;
    public UIButton OneKeyGetCashBtn_UIButton;
    public UILabel RefreshBtnLb_UILabel;
    public UIGrid MenuGtid_UIGrid;
    public UILabel RefreshLb_UILabel;
    public UIGrid TabGrid_UIGrid;
    public UILabel DescLb_UILabel;
    public UIButton PopupBtn_UIButton;
    public UILabel PopupLb_UILabel;
    public GameObject PageGrounp;
    public UIButton ChoiseCount_UIButton;
    public UILabel CountLb_UILabel;
    public UIButton AddCountBtn_UIButton;
    public UIButton ReduceCountBtn_UIButton;
    public Transform PopupPos_Transform;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        BuyGroup = root.FindGameObject("BuyGroup");
        SellGroup = root.FindGameObject("SellGroup");
        BuyGroupBtn_UIButton = root.FindScript<UIButton>("BuyGroupBtn");
        SellGroupBtn_UIButton = root.FindScript<UIButton>("SellGroupBtn");
        CashLb_UILabel = root.FindScript<UILabel>("CashGroup/CashLb");
        AddCashBtn_UIButton = root.FindScript<UIButton>("CashGroup/AddCashBtn");
        BuyScrollView_UIScrollView = root.FindScript<UIScrollView>("BuyGroup/BuyScrollView");
        BuyGoodsGrid_UIGrid = root.FindScript<UIGrid>("BuyGroup/BuyScrollView/BuyGoodsGrid");
        RefreshBtn_UIButton = root.FindScript<UIButton>("BuyGroup/RefreshBtn");
        OptionScrollView_UIScrollView = root.FindScript<UIScrollView>("BuyGroup/OptionScrollView");
        OptionGrid_UIGrid = root.FindScript<UIGrid>("BuyGroup/OptionScrollView/OptionGrid");
        BuyItemBtn_UIButton = root.FindScript<UIButton>("BuyGroup/BuyItemBtn");
        PageLb_UILabel = root.FindScript<UILabel>("BuyGroup/PageGrounp/PageLb");
        NextBtn_UIButton = root.FindScript<UIButton>("BuyGroup/PageGrounp/NextBtn");
        LastBtn_UIButton = root.FindScript<UIButton>("BuyGroup/PageGrounp/LastBtn");
        SellTipBtn_UIButton = root.FindScript<UIButton>("SellGroup/SellTipBtn");
        SellItemScrollView_UIScrollView = root.FindScript<UIScrollView>("SellGroup/SellItemScrollView");
        SellItemGrid_UIGrid = root.FindScript<UIGrid>("SellGroup/SellItemScrollView/SellItemGrid");
        OneKeySellBtn_UIButton = root.FindScript<UIButton>("SellGroup/OneKeySellBtn");
        OneKeyGetCashBtn_UIButton = root.FindScript<UIButton>("SellGroup/OneKeyGetCashBtn");
        RefreshBtnLb_UILabel = root.FindScript<UILabel>("BuyGroup/RefreshBtn/RefreshBtnLb");
        MenuGtid_UIGrid = root.FindScript<UIGrid>("BuyGroup/BuyScrollView/MenuGtid");
        RefreshLb_UILabel = root.FindScript<UILabel>("BuyGroup/RefreshBtn/RefreshLb");
        TabGrid_UIGrid = root.FindScript<UIGrid>("TabGrid");
        DescLb_UILabel = root.FindScript<UILabel>("BuyGroup/DescLb");
        PopupBtn_UIButton = root.FindScript<UIButton>("BuyGroup/PopupBtn");
        PopupLb_UILabel = root.FindScript<UILabel>("BuyGroup/PopupBtn/PopupLb");
        PageGrounp = root.FindGameObject("BuyGroup/PageGrounp");
        ChoiseCount_UIButton = root.FindScript<UIButton>("ChoiseCount");
        CountLb_UILabel = root.FindScript<UILabel>("ChoiseCount/CountLb");
        AddCountBtn_UIButton = root.FindScript<UIButton>("ChoiseCount/AddCountBtn");
        ReduceCountBtn_UIButton = root.FindScript<UIButton>("ChoiseCount/ReduceCountBtn");
        PopupPos_Transform = root.FindTrans("BuyGroup/PopupBtn/PopupPos");

    }
    #endregion
}
