// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class PitchPutawayAgainView : BaseView
{
    public const string NAME ="PitchPutawayAgainView";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UILabel LvLb_UILabel;
    public UILabel NameLb_UILabel;
    public UILabel DescLb_UILabel;
    public UIButton CloseBtn_UIButton;
    public UISprite CashIcon_UISprite;
    public UIButton PriceAddBtn_UIButton;
    public UIButton PriceReduceBtn_UIButton;
    public UILabel PriceLb_UILabel;
    public UILabel TotalLb_UILabel;
    public UISprite TotalIcon_UISprite;
    public UILabel HandleLb_UILabel;
    public UISprite HandleIcon_UISprite;
    public UIButton SoldOutBtn_UIButton;
    public UIButton PutawayBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        LvLb_UILabel = root.FindScript<UILabel>("LvLb");
        NameLb_UILabel = root.FindScript<UILabel>("NameLb");
        DescLb_UILabel = root.FindScript<UILabel>("DescLb");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        CashIcon_UISprite = root.FindScript<UISprite>("Price/CashIcon");
        PriceAddBtn_UIButton = root.FindScript<UIButton>("Price/PriceAddBtn");
        PriceReduceBtn_UIButton = root.FindScript<UIButton>("Price/PriceReduceBtn");
        PriceLb_UILabel = root.FindScript<UILabel>("Price/PriceLb");
        TotalLb_UILabel = root.FindScript<UILabel>("Total/TotalLb");
        TotalIcon_UISprite = root.FindScript<UISprite>("Total/TotalIcon");
        HandleLb_UILabel = root.FindScript<UILabel>("Handle/HandleLb");
        HandleIcon_UISprite = root.FindScript<UISprite>("Handle/HandleIcon");
        SoldOutBtn_UIButton = root.FindScript<UIButton>("SoldOutBtn");
        PutawayBtn_UIButton = root.FindScript<UIButton>("PutawayBtn");

    }
    #endregion
}
