// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UniRx;




public partial interface ITeamBeInviteView{
         UniRx.IObservable<Unit> OnCancelButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnOKButton_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnShrinkBtn_UIButtonClick{get;}

    
}

public sealed partial class TeamBeInviteView :
    BaseView,ITeamBeInviteView
{
    public const string NAME ="TeamBeInviteView";

    #region Element Bindings

    /// bind gameobject
        private GameObject TeamInvitationItem;
    private UIButton CancelButton_UIButton;
    private UIButton OKButton_UIButton;
    private UILabel InfoLabel2_UILabel;
    private UILabel CancelLabel_UILabel;
    private UIButton ShrinkBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
                TeamInvitationItem = root.FindGameObject("ContentFrame/TeamInvitationItem");
        CancelButton_UIButton = root.FindScript<UIButton>("ContentFrame/CancelButton");
        OKButton_UIButton = root.FindScript<UIButton>("ContentFrame/OKButton");
        InfoLabel2_UILabel = root.FindScript<UILabel>("ContentFrame/InfoLabel2");
        CancelLabel_UILabel = root.FindScript<UILabel>("ContentFrame/CancelButton/CancelLabel");
        ShrinkBtn_UIButton = root.FindScript<UIButton>("ShrinkBtn");

    }
    #endregion

    #region Event
    protected override void InitReactiveEvents(){
            CancelButton_UIButtonEvt = CancelButton_UIButton.AsObservable();
    OKButton_UIButtonEvt = OKButton_UIButton.AsObservable();
    ShrinkBtn_UIButtonEvt = ShrinkBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
                CancelButton_UIButtonEvt = CancelButton_UIButtonEvt.CloseOnceNull();
        OKButton_UIButtonEvt = OKButton_UIButtonEvt.CloseOnceNull();
        ShrinkBtn_UIButtonEvt = ShrinkBtn_UIButtonEvt.CloseOnceNull();

    }

        private Subject<Unit> CancelButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCancelButton_UIButtonClick{
        get {return CancelButton_UIButtonEvt;}
    }

    private Subject<Unit> OKButton_UIButtonEvt;
    public UniRx.IObservable<Unit> OnOKButton_UIButtonClick{
        get {return OKButton_UIButtonEvt;}
    }

    private Subject<Unit> ShrinkBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnShrinkBtn_UIButtonClick{
        get {return ShrinkBtn_UIButtonEvt;}
    }


    
    
    #endregion
}
