//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TeamApplicationUnitedItem.
/// </summary>
public partial class TeamApplicationUnitedItem : BaseView
{
	public const string NAME ="TeamApplicationUnitedItem";
	public UIGrid ItemGrid_UIGrid;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		ItemGrid_UIGrid = root.Find("ItemGrid").GetComponent<UIGrid>();
	}
}
