// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GuildEventItemCellController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGuildEventItemCellController
{

}

public partial class GuildEventItemCellController:MonolessViewController<GuildEventItemCell>, IGuildEventItemCellController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
