// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  GuildMessageItemCellController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IGuildMessageItemCellController
{

}

public partial class GuildMessageItemCellController:MonolessViewController<GuildMessageItemCell>, IGuildMessageItemCellController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
