// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EquipmentItemCellController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IEquipmentItemCellController
{

}

public partial class EquipmentItemCellController:MonolessViewController<EquipmentItemCell>, IEquipmentItemCellController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
