// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EmbebGroupFristShowAttrController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IEmbebGroupFristShowAttrController
{

}

public partial class EmbebGroupFristShowAttrController:MonolessViewController<EmbebGroupFristShowAttr>, IEmbebGroupFristShowAttrController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
