// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EquipmentEmbedController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IEquipmentEmbedController
{

}

public partial class EquipmentEmbedController:MonolessViewController<EquipmentEmbed>, IEquipmentEmbedController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
