// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  HoleItemLittleController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IHoleItemLittleController
{

}

public partial class HoleItemLittleController:MonolessViewController<HoleItemLittle>, IHoleItemLittleController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
