// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class RankingItemCell : BaseView
{
    public const string NAME ="RankingItemCell";

    #region Element Bindings

    /// bind gameobject
    public UISprite rankMark_UISprite;
    public UILabel FirstLabel_UILabel;
    public UILabel SecondLabel_UILabel;
    public UILabel ThirdLabel_UILabel;
    public UILabel FurthLabel_UILabel;
    public UISprite factionMark_UISprite;
    public UILabel FifthLabel_UILabel;
    public UIButton RankingItemCell_UIButton;
    public UISprite bg_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        rankMark_UISprite = root.FindScript<UISprite>("rankMark");
        FirstLabel_UILabel = root.FindScript<UILabel>("Label/FirstLabel");
        SecondLabel_UILabel = root.FindScript<UILabel>("Label/SecondLabel");
        ThirdLabel_UILabel = root.FindScript<UILabel>("Label/ThirdLabel");
        FurthLabel_UILabel = root.FindScript<UILabel>("Label/FurthLabel");
        factionMark_UISprite = root.FindScript<UISprite>("factionMark");
        FifthLabel_UILabel = root.FindScript<UILabel>("Label/FifthLabel");
        RankingItemCell_UIButton = root.FindScript<UIButton>("");
        bg_UISprite = root.FindScript<UISprite>("bg");

    }
    #endregion
}
