// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SubRankingPage : BaseView
{
    public const string NAME ="SubRankingPage";

    #region Element Bindings

    /// bind gameobject
    public UITable OptionTable_UITable;
    public UITable SecondTable_UITable;
    public UIGrid TabBtn_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        OptionTable_UITable = root.FindScript<UITable>("MenuGroup/MenuScollView/OptionTable");
        SecondTable_UITable = root.FindScript<UITable>("MenuGroup/SecondTable");
        TabBtn_UIGrid = root.FindScript<UIGrid>("TabBtn");

    }
    #endregion
}
