// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class RoleSkillView : BaseView
{
    public const string NAME ="RoleSkillView";

    #region Element Bindings

    /// bind gameobject
    //public UILabel lblTitleName_UILabel;
    public UITable tabBtn_UIGrid;
    public Transform Content_Transform;
    public UIButton CloseBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        //lblTitleName_UILabel = root.FindScript<UILabel>("BaseTabWindow/TitleNameSprite");
        tabBtn_UIGrid = root.FindScript<UITable>("BaseMainWindow/TabGroup");
        Content_Transform = root.FindTrans("Content");
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseMainWindow/CloseBtn");
    }
    #endregion
}
