// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewFetterView : BaseView
{
    public const string NAME ="CrewFetterView";

    #region Element Bindings

    /// bind gameobject
    public UISprite FetterAttrIcon_UISprite;
    public UILabel FetterName_UILabel;
    public UIButton activateBtn_UIButton;
    public UILabel activateBtn_Label_UILabel;
    public UILabel FetterParnerInfoNames_UILabel;
    public UILabel FetterDetailInfo_UILabel;
    public Transform FetterList_Transform;
    public UISprite SelfIcon_UISprite;
    public UIButton CrewFetterTipBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        FetterAttrIcon_UISprite = root.FindScript<UISprite>("FetterInfoGroup/Bg/FetterAttrIcon");
        FetterName_UILabel = root.FindScript<UILabel>("FetterInfoGroup/Bg/FetterName");
        activateBtn_UIButton = root.FindScript<UIButton>("FetterInfoGroup/Bg/activateBtn");
        activateBtn_Label_UILabel = root.FindScript<UILabel>("FetterInfoGroup/Bg/activateBtn/activateBtn_Label");
        FetterParnerInfoNames_UILabel = root.FindScript<UILabel>("FetterInfoGroup/Bg/FetterParnerInfoNames");
        FetterDetailInfo_UILabel = root.FindScript<UILabel>("FetterInfoGroup/Bg/FetterDetailInfo");
        FetterList_Transform = root.FindTrans("PartnerFetterMiddleShowGroup/FetterList");
        SelfIcon_UISprite = root.FindScript<UISprite>("PartnerFetterMiddleShowGroup/SelfParnertInfoItem/SelfIcon");
        CrewFetterTipBtn_UIButton = root.FindScript<UIButton>("CrewFetterTipBtn");

    }
    #endregion
}
