// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewFetterItemIcon : BaseView
{
    public const string NAME ="CrewFetterItemIcon";

    #region Element Bindings

    /// bind gameobject
    public UISprite Border_UISprite;
    public UISprite Icon_UISprite;
    public UISprite CheckMark_UISprite;
    public UISprite GrayMask_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Border_UISprite = root.FindScript<UISprite>("Border");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        CheckMark_UISprite = root.FindScript<UISprite>("CheckMark");
        GrayMask_UISprite = root.FindScript<UISprite>("GrayMask");

    }
    #endregion
}
