// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewFavorLabelController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ICrewFavorLabelController
{

}

public partial class CrewFavorLabelController:MonolessViewController<CrewFavorLabel>, ICrewFavorLabelController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
