// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class StrengthContainerView : BaseView
{
    public const string NAME ="StrengthContainerView";

    #region Element Bindings

    /// bind gameobject
    public Transform PartnerDevelopView;
    public GameObject DevelopTipsGroup;
    public UIButton DevelopButton_UIButton;
    public UITable InfoTable_UITable;
    public Transform ExpendGrid_Transform;
    public Transform TrainView_Transform;
    public UIGrid StrengthenPageGrid_UIGrid;
    public PageScrollView DevelopStrengthGrid_PageScrollView;
    public UIButton TipButton_UIButton;
    public Transform PartnerStrengthenView;
    public UIButton StrengthTipBtn_UIButton;
    public Transform StrengthMasAnchor_Transform;
    public UIButton StrengthButton_UIButton;
    public UILabel BeforeStrength_UILabel;
    public UILabel AfterStrength_UILabel;
    public UIButton CheckBtn_UIButton;
    public UIGrid StrengthInfoGrid_UIGrid;
    public GameObject YellowLineGroup;
    public GameObject LightGroup;
    public GameObject Consume;
    public GameObject BestStrengthLab;
    public GameObject devLigth;
    public UISprite QualityIcon_UISprite;
    public GameObject BestDevelopLab;
    public GameObject DevConsume;
    public GameObject DevLightGroup;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        PartnerDevelopView = root.FindTrans("Phasegroup/DevelopStrengthGrid/PartnerDevelopView");
        DevelopTipsGroup = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevelopTipsGroup");
        DevelopButton_UIButton = root.FindScript<UIButton>("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevelopButton");
        InfoTable_UITable = root.FindScript<UITable>("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/PropertyGroup/InfoTable");
        ExpendGrid_Transform = root.FindTrans("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevConsume/ExpendGrid");
        TrainView_Transform = root.FindTrans("Phasegroup/DevelopStrengthGrid/TrainingView");
        StrengthenPageGrid_UIGrid = root.FindScript<UIGrid>("StrengthenPageGrid");
        DevelopStrengthGrid_PageScrollView = root.FindScript<PageScrollView>("Phasegroup/DevelopStrengthGrid");
        TipButton_UIButton = root.FindScript<UIButton>("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/TipButton");
        PartnerStrengthenView = root.FindTrans("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView");
        StrengthTipBtn_UIButton = root.FindScript<UIButton>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/StrengthTipBtn");
        StrengthMasAnchor_Transform = root.FindTrans("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/Consume/StrengthMasAnchor");
        StrengthButton_UIButton = root.FindScript<UIButton>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/StrengthButton");
        BeforeStrength_UILabel = root.FindScript<UILabel>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/StrengthLb/BeforeStrength");
        AfterStrength_UILabel = root.FindScript<UILabel>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/StrengthLb/AfterStrength");
        CheckBtn_UIButton = root.FindScript<UIButton>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/StrengthLb/CheckBtn");
        StrengthInfoGrid_UIGrid = root.FindScript<UIGrid>("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/PropertyGroup/StrengthInfoGrid");
        YellowLineGroup = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/YellowLineGroup");
        LightGroup = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/LightGroup");
        Consume = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/Consume");
        BestStrengthLab = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerStrengthenView/PartnerStrengthGroup/BestStrengthLab");
        devLigth = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevLightGroup/devLigth");
        QualityIcon_UISprite = root.FindScript<UISprite>("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevLightGroup/QualityIcon");
        BestDevelopLab = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/BestDevelopLab");
        DevConsume = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevConsume");
        DevLightGroup = root.FindGameObject("Phasegroup/DevelopStrengthGrid/PartnerDevelopView/PartnerDevelopGroup/DevLightGroup");

    }
    #endregion
}
