// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class AssistChooseView : BaseView
{
    public const string NAME ="AssistChooseView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CarryCook_UIButton;
    public UIButton GrailCook_UIButton;
    public UIButton LeadForce_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CarryCook_UIButton = root.FindScript<UIButton>("CarryCook");
        GrailCook_UIButton = root.FindScript<UIButton>("GrailCook");
        LeadForce_UIButton = root.FindScript<UIButton>("LeadForce");

    }
    #endregion
}
