// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class AssistSkillForgetView : BaseView
{
    public const string NAME ="AssistSkillForgetView";

    #region Element Bindings

    /// bind gameobject
    public UILabel ContentLb_UILabel;
    public UISprite CostSprite_UISprite;
    public UILabel CostLabel_UILabel;
    public UIButton OKButton_UIButton;
    public UIButton CancelButton_UIButton;
    public Transform Forget_Transform;
    public UILabel FirstForget_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ContentLb_UILabel = root.FindScript<UILabel>("ContentLb");
        CostSprite_UISprite = root.FindScript<UISprite>("ForgetWidget/CostSprite");
        CostLabel_UILabel = root.FindScript<UILabel>("ForgetWidget/CostLabel");

        OKButton_UIButton = root.FindScript<UIButton>("OKButton");
        CancelButton_UIButton = root.FindScript<UIButton>("CancelButton");
        Forget_Transform = root.FindScript<Transform>("ForgetWidget");
        FirstForget_UILabel = root.FindScript<UILabel>("FirstForget");
    }
    #endregion
}
