// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class AssistDelegateCrewView : BaseView
{
    public const string NAME ="AssistDelegateCrewView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UIButton ConfirmBtn_UIButton;
    public UIGrid BtnGrid_UIGrid;
    public UIGrid IconGrid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        ConfirmBtn_UIButton = root.FindScript<UIButton>("ConfirmBtn");
        BtnGrid_UIGrid = root.FindScript<UIGrid>("BtnGrid");
        IconGrid_UIGrid = root.FindScript<UIGrid>("ScrollView/IconGrid");

    }
    #endregion
}
