// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class AssistDelegateFriendView : BaseView
{
    public const string NAME ="AssistDelegateFriendView";

    #region Element Bindings

    /// bind gameobject
    public UIGrid Grid_UIGrid;
    public UIGrid TabGird_UIGrid;
    public UIButton CloseBtn_UIButton;
    public Transform NoFriendTips;
    public UITexture Texture;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        NoFriendTips = root.FindTrans("NoFriendTips");
        Grid_UIGrid = root.FindScript<UIGrid>("DetailBg/ScrollView/Grid");
        TabGird_UIGrid = root.FindScript<UIGrid>("TabGird");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        Texture = root.FindScript<UITexture>("NoFriendTips/Texture");

    }
    #endregion
}
