//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SceneFadeEffectPrefab.
/// </summary>
public partial class SceneFadeEffectPrefab : BaseView
{
    public const string NAME ="SceneFadeEffectPrefab";
    public UITexture bgTexture;
    public UISlider loadingSlider;
    public UILabel tipLbl;
    public TweenAlpha alphaTween;
    public UILabel loadingLbl;
    public Transform loadingSliderThumb;
    public Transform tipBg_Transform;
    public CameraTextrue LoadSceneEffect;
    public GameObject LoadSceneEffectGO;
    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
        bgTexture = root.Find("bgTexture").GetComponent<UITexture>();
        loadingSlider = root.Find("loadingSlider").GetComponent<UISlider>();
        tipLbl = root.Find("tipBg/tipLbl").GetComponent<UILabel>();
        alphaTween = root.Find("fadeBg").GetComponent<TweenAlpha>();
        loadingLbl = root.Find("loadingSlider/LoadingLabel").GetComponent<UILabel>();
        loadingSliderThumb = root.Find("loadingSlider/loadingSliderThumb");
        tipBg_Transform = root.Find("tipBg");
        LoadSceneEffect = root.gameObject.FindScript<CameraTextrue>("game_eff_posui01");
		LoadSceneEffectGO = root.gameObject.FindGameObject("game_eff_posui01/game_eff_posui_01");
    }
}
