// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CmomerceView : BaseView
{
    public const string NAME ="CmomerceView";

    #region Element Bindings

    /// bind gameobject
    public UIButton SellGroupBtn_UIButton;
    public UIButton BuyGroupBtn_UIButton;
    public UILabel ItemNameLb_UILabel;
    public UILabel ItemDescLb_UILabel;
    public GameObject Texture;
    public UILabel NumLb_UILabel;
    public UIButton AddNumBtn_UIButton;
    public UIButton ReduceNumBtn_UIButton;
    public UILabel TotalLb_UILabel;
    public UISprite TotalIcon_UISprite;
    public UILabel CashLb_UILabel;
    public UISprite CashIcon_UISprite;
    public UIButton BuyCashBtn_UIButton;
    public UIButton BuyBtn_UIButton;
    public UIButton SellBtn_UIButton;
    public GameObject BuyGroup;
    public UIScrollView BuyScollView_UIScrollView;
    public UITable OptionTable_UITable;
    public UIScrollView BuyItemScrollView_UIScrollView;
    public UIGrid BuyItemGrid_UIGrid;
    public GameObject SellGroup;
    public UIScrollView SellScrollView_UIScrollView;
    public UIGrid SellGrid_UIGrid;
    public UITable SecondTable_UITable;
    public UIButton OpenInputBtn_UIButton;
    public UIEventListener AddNumBtn_UIEventListener;
    public UIEventListener ReduceNumBtn_UIEventListener;
    public UIGrid TabBtn_UIGrid;
    public UISprite PropsIcon_UISprite;
    public UISprite IconBG_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        SellGroupBtn_UIButton = root.FindScript<UIButton>("SellGroupBtn");
        BuyGroupBtn_UIButton = root.FindScript<UIButton>("BuyGroupBtn");
        ItemNameLb_UILabel = root.FindScript<UILabel>("RightGroup/ItemNameLb");
        ItemDescLb_UILabel = root.FindScript<UILabel>("RightGroup/ItemDescLb");
        Texture = root.FindGameObject("RightGroup/Texture");
        NumLb_UILabel = root.FindScript<UILabel>("RightGroup/Num/NumLb");
        AddNumBtn_UIButton = root.FindScript<UIButton>("RightGroup/Num/AddNumBtn");
        ReduceNumBtn_UIButton = root.FindScript<UIButton>("RightGroup/Num/ReduceNumBtn");
        TotalLb_UILabel = root.FindScript<UILabel>("RightGroup/Total/TotalLb");
        TotalIcon_UISprite = root.FindScript<UISprite>("RightGroup/Total/TotalIcon");
        CashLb_UILabel = root.FindScript<UILabel>("RightGroup/Cash/CashLb");
        CashIcon_UISprite = root.FindScript<UISprite>("RightGroup/Cash/CashIcon");
        BuyCashBtn_UIButton = root.FindScript<UIButton>("RightGroup/Cash/BuyCashBtn");
        BuyBtn_UIButton = root.FindScript<UIButton>("RightGroup/BuyBtn");
        SellBtn_UIButton = root.FindScript<UIButton>("SellGroup/SellBtn");
        BuyGroup = root.FindGameObject("BuyGroup");
        BuyScollView_UIScrollView = root.FindScript<UIScrollView>("BuyGroup/BuyScollView");
        OptionTable_UITable = root.FindScript<UITable>("BuyGroup/BuyScollView/OptionTable");
        BuyItemScrollView_UIScrollView = root.FindScript<UIScrollView>("BuyGroup/BuyItemScrollView");
        BuyItemGrid_UIGrid = root.FindScript<UIGrid>("BuyGroup/BuyItemScrollView/BuyItemGrid");
        SellGroup = root.FindGameObject("SellGroup");
        SellScrollView_UIScrollView = root.FindScript<UIScrollView>("SellGroup/SellScrollView");
        SellGrid_UIGrid = root.FindScript<UIGrid>("SellGroup/SellScrollView/SellGrid");
        SecondTable_UITable = root.FindScript<UITable>("BuyGroup/SecondTable");
        OpenInputBtn_UIButton = root.FindScript<UIButton>("RightGroup/Num/NumBtn");
        AddNumBtn_UIEventListener = root.FindScript<UIEventListener>("RightGroup/Num/AddNumBtn");
        ReduceNumBtn_UIEventListener = root.FindScript<UIEventListener>("RightGroup/Num/ReduceNumBtn");
        TabBtn_UIGrid = root.FindScript<UIGrid>("TabBtn");
        PropsIcon_UISprite = root.FindScript<UISprite>("RightGroup/PropsIcon");
        IconBG_UISprite = root.FindScript<UISprite>("RightGroup/PropsIcon/IconBG");

    }
    #endregion
}
