// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  BattleReadyViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IBattleReadyViewController
{

}

public partial class BattleReadyViewController:MonoViewController<BattleReadyView>, IBattleReadyViewController
{


}
