// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  SimpleNumberInputerController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class SimpleNumberInputerController:MonoViewController<SimpleNumberInputer>
{
    

}
