// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UniRx;




public partial interface IChatChannelToggleView {
         UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnConfirmBtn_UIButtonClick{get;}

    
}

public sealed partial class ChatChannelToggleView :
    BaseView,IChatChannelToggleView
{
    public const string NAME ="ChatChannelToggleView";

    #region Element Bindings

    /// bind gameobject
        public UIGrid Grid_Top_UIGrid;
    public UIButton CloseBtn_UIButton;
    public UIGrid Grid_Bottom_UIGrid;
    public UIButton ConfirmBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
                Grid_Top_UIGrid = root.FindScript<UIGrid>("Content/Top/Grid_Top");
        CloseBtn_UIButton = root.FindScript<UIButton>("Content/CloseBtn");
        Grid_Bottom_UIGrid = root.FindScript<UIGrid>("Content/Bottom/Grid_Bottom");
        ConfirmBtn_UIButton = root.FindScript<UIButton>("Content/ConfirmBtn");

    }
    #endregion

    #region Event
    protected override void InitReactiveEvents(){
            CloseBtn_UIButtonEvt = CloseBtn_UIButton.AsObservable();
    ConfirmBtn_UIButtonEvt = ConfirmBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
                CloseBtn_UIButtonEvt = CloseBtn_UIButtonEvt.CloseOnceNull();
        ConfirmBtn_UIButtonEvt = ConfirmBtn_UIButtonEvt.CloseOnceNull();

    }

        private Subject<Unit> CloseBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{
        get {return CloseBtn_UIButtonEvt;}
    }

    private Subject<Unit> ConfirmBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnConfirmBtn_UIButtonClick{
        get {return ConfirmBtn_UIButtonEvt;}
    }


    
    
    #endregion
}
