//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleActionQueueItem.
/// </summary>
public partial class BattleActionQueueItem : BaseView
{
	public const string NAME ="BattleActionQueueItem";
	public UISprite SpriteType_UISprite;
	public UILabel LabelName_UILabel;
	public TweenAlpha SpriteHightLight_TweenAlpha;
	public UISprite SpriteDesc_UISprite;
	public UISprite SpriteHead_UISprite;
	public UISprite SpriteDescBG_UISprite;
    public UISprite BattleReward_UISprite;
    public UISprite BattleRewardBG_UISprite;
    public TweenAlpha SpriteType_TweenAlpha;
	public GameObject SpriteHightLight;
    public UILabel RewardLabel_UILabell;

    protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		SpriteType_UISprite = root.Find("SpriteType").GetComponent<UISprite>();
		LabelName_UILabel = root.Find("LabelName").GetComponent<UILabel>();
		SpriteHightLight_TweenAlpha = root.Find("SpriteHightLight").GetComponent<TweenAlpha>();
        SpriteDesc_UISprite = root.Find("CntrDesc/SpriteDesc_UISprite").GetComponent<UISprite>();
		SpriteHead_UISprite = root.Find("SpriteHead").GetComponent<UISprite>();
		SpriteDescBG_UISprite = root.Find("CntrDesc/SpriteDescBG").GetComponent<UISprite>();
		SpriteType_TweenAlpha = root.Find("SpriteType").GetComponent<TweenAlpha>();
		SpriteHightLight = root.Find("SpriteHightLight").gameObject;
        BattleReward_UISprite = root.Find("BattleReward/RewardIcon").GetComponent<UISprite>();
        RewardLabel_UILabell = root.Find("BattleReward/RewardLabel").GetComponent<UILabel>();
        BattleRewardBG_UISprite = root.Find("BattleReward").GetComponent<UISprite>();
    }
}
