//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleOrderEditorCell.
/// </summary>
public partial class BattleOrderEditorCell : BaseView
{
	public const string NAME ="BattleOrderEditorCell";
	public UIButton OrderButton;
	public UISprite panSprite;
	public UISprite bigAddSprite;
	public UISprite smallAddSprite;
	public UILabel btnLabel;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		OrderButton = root.Find("OrderButton").GetComponent<UIButton>();
		panSprite = root.Find("panSprite").GetComponent<UISprite>();
		bigAddSprite = root.Find("bigAddSprite").GetComponent<UISprite>();
		smallAddSprite = root.Find("smallAddSprite").GetComponent<UISprite>();
		btnLabel = root.Find("OrderButton/btnLabel").GetComponent<UILabel>();
	}
}
