//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleTotalDamageHealView.
/// </summary>
public partial class BattleTotalDamageHealView : BaseView
{
	public const string NAME ="BattleTotalDamageHealView";
	public GameObject CntrLeftDamageInfoUI;
	public UILabel LabelDamageInfo_UILabel;
	public UILabel LabelHealInfo_UILabel;
	public UISprite CntrLeftDamageInfoUIBG_UISprite;
	public TweenAlpha CntrLeftDamageInfoUI_TweenAlpha;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		CntrLeftDamageInfoUI = root.Find("CntrLeftDamageInfoUI").gameObject;
		LabelDamageInfo_UILabel = root.Find("CntrLeftDamageInfoUI/LabelDamageInfo").GetComponent<UILabel>();
		LabelHealInfo_UILabel = root.Find("CntrLeftDamageInfoUI/LabelHealInfo").GetComponent<UILabel>();
		CntrLeftDamageInfoUIBG_UISprite = root.Find("CntrLeftDamageInfoUI/CntrLeftDamageInfoUIBG").GetComponent<UISprite>();
		CntrLeftDamageInfoUI_TweenAlpha = root.Find("CntrLeftDamageInfoUI").GetComponent<TweenAlpha>();
	}
}
