// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BattlePVEFailView : BaseView
{
    public const string NAME ="BattlePVEFailView";

    #region Element Bindings

    /// bind gameobject
    public UIButton UpGradeBtn_UIButton;
    public UIButton UpSkillGradeBtn_UIButton;
    public UIButton CrewBtn_UIButton;
    public UIButton EquipmentBtn_UIButton;
    public UIPanel BattlePVEFailView_UIPanel;
    public UIButton CloseWidget_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        UpGradeBtn_UIButton = root.FindScript<UIButton>("UpGradeBtn");
        UpSkillGradeBtn_UIButton = root.FindScript<UIButton>("UpSkillGradeBtn");
        CrewBtn_UIButton = root.FindScript<UIButton>("CrewBtn");
        EquipmentBtn_UIButton = root.FindScript<UIButton>("EquipmentBtn");
        BattlePVEFailView_UIPanel = root.FindScript<UIPanel>("");
        CloseWidget_UIButton = root.FindScript<UIButton>("CloseWidget");

    }
    #endregion
}
