// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BattleActionQueueView : BaseView
{
    public const string NAME ="BattleActionQueueView";

    #region Element Bindings

    /// bind gameobject
    public UIGrid CntrNamesGrid_UIGrid;
    public UILabel RoundNumberLabel_UILabel;
    public UIButton AttributeIconButton_UIButton;
    public GameObject AttributeDesPanel_Gameobject;
    public UIButton colloderButton_UIButton;
    public UILabel AttributeDesLabel_UILabel;
    public UISprite EnemyArrow_UISprite;
    public UISprite SelfArrow_UISprite;
    public UISprite EnemyFormation_UISprite;
    public UISprite SelfFormation_UISprite;
    public UIButton FormationInfoBtn_UIButton;
    public UIPanel FormationInfoUI_UIPanel;
    public GameObject BattleFormationInfoView;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CntrNamesGrid_UIGrid = root.FindScript<UIGrid>("CntrNames/CntrNamesGrid");
        RoundNumberLabel_UILabel = root.FindScript<UILabel>("RoundNumberLabel");
        AttributeIconButton_UIButton = root.FindScript<UIButton>("UI/TopUI/BG/AttributeIcon");
        AttributeDesPanel_Gameobject = root.FindGameObject("AttributeDesPanel");
        colloderButton_UIButton = root.FindScript<UIButton>("AttributeDesPanel/colloderButton");
        AttributeDesLabel_UILabel = root.FindScript<UILabel>("AttributeDesPanel/BG/Label");
        EnemyArrow_UISprite = root.FindScript<UISprite>("UI/TopUI/BG/Describe/EnemyArrow");
        SelfArrow_UISprite = root.FindScript<UISprite>("UI/TopUI/BG/Describe/SelfArrow");
        EnemyFormation_UISprite = root.FindScript<UISprite>("UI/TopUI/BG/Describe/EnemyFormation");
        SelfFormation_UISprite = root.FindScript<UISprite>("UI/TopUI/BG/Describe/SelfFormation");
        FormationInfoBtn_UIButton = root.FindScript<UIButton>("UI/TopUI/BG/Describe/FormationInfoBtn");
        FormationInfoUI_UIPanel = root.FindScript<UIPanel>("UI/FormationInfoUI");
        BattleFormationInfoView = root.FindGameObject("UI/FormationInfoUI");

    }
    #endregion
}
