// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BattleItemView : BaseView
{
    public const string NAME ="BattleItemView";

    #region Element Bindings

    /// bind gameobject
    public UILabel DesLabel_UILabel;
    public GameObject tabBtn;
    public UIGrid Container_UIGrid;
    public UIScrollView Content_UIScrollView;
    public GameObject Container;
    public UILabel NameLabel_UILabel;
    public UILabel LeftTimeLabel_UILabel;
    public UIButton ConfirmButton_UIButton;
    public UILabel btnLabel_UILabel;
    public UILabel TipLabel_UILabel;
    public UIPanel BattleItemView_UIPanel;
    public UIPanel scrollView_UIPanel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        DesLabel_UILabel = root.FindScript<UILabel>("DesLabel");
        tabBtn = root.FindGameObject("Content/tabBtn");
        Container_UIGrid = root.FindScript<UIGrid>("Content/scrollView/Container");
        Content_UIScrollView = root.FindScript<UIScrollView>("Content/scrollView");
        Container = root.FindGameObject("Content/scrollView/Container");
        NameLabel_UILabel = root.FindScript<UILabel>("NameLabel");
        LeftTimeLabel_UILabel = root.FindScript<UILabel>("LeftTimeLabel");
        ConfirmButton_UIButton = root.FindScript<UIButton>("ConfirmButton");
        btnLabel_UILabel = root.FindScript<UILabel>("ConfirmButton/btnLabel");
        TipLabel_UILabel = root.FindScript<UILabel>("TipLabel");
        BattleItemView_UIPanel = root.FindScript<UIPanel>("");
        scrollView_UIPanel = root.FindScript<UIPanel>("Content/scrollView");

    }
    #endregion
}
