// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  QuartzForgeController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IQuartzForgeController
{
     UniRx.IObservable<Unit> OnCommonBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnStrengthBtn_UIButtonClick{get;}

}

public partial class QuartzForgeController:MonolessViewController<QuartzForge>, IQuartzForgeController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        CommonBtn_UIButtonEvt = View.CommonBtn_UIButton.AsObservable();
        StrengthBtn_UIButtonEvt = View.StrengthBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        CommonBtn_UIButtonEvt = CommonBtn_UIButtonEvt.CloseOnceNull();
        StrengthBtn_UIButtonEvt = StrengthBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> CommonBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCommonBtn_UIButtonClick{
        get {return CommonBtn_UIButtonEvt;}
    }

    private Subject<Unit> StrengthBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnStrengthBtn_UIButtonClick{
        get {return StrengthBtn_UIButtonEvt;}
    }


}
