// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  QuartzMagicSliderController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IQuartzMagicSliderController
{

}

public partial class QuartzMagicSliderController:MonolessViewController<QuartzMagicSlider>, IQuartzMagicSliderController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
