// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using Assets.Standard_Assets.NGUI.CustomExtension.UI;

public sealed partial class BaseProgressBar : BaseView
{
    public const string NAME ="BaseProgressBar";

    #region Element Bindings

    /// bind gameobject
    public UISprite Overlay_UISprite;
    public UILabel Label_UILabel;
    public CProgressBar BaseProgressBar_CProgressBar;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Overlay_UISprite = root.FindScript<UISprite>("Overlay");
        Label_UILabel = root.FindScript<UILabel>("Label");
        BaseProgressBar_CProgressBar = root.FindScript<CProgressBar>("");

    }
    #endregion
}
