// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class BaseTipWindow : BaseView
{
    public const string NAME ="BaseTipWindow";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public GameObject Anchor;
    public UISprite BackGround_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        Anchor = root.FindGameObject("Anchor");
        BackGround_UISprite = root.FindScript<UISprite>("BackGround");

    }
    #endregion
}
