// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BattleReadyPlayerItem : BaseView
{
    public const string NAME ="BattleReadyPlayerItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UILabel NameLb_UILabel;
    public UILabel LvLb_UILabel;
    public UISprite Attribute_UISprite;
    public UISprite Faction_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        NameLb_UILabel = root.FindScript<UILabel>("NameLb");
        LvLb_UILabel = root.FindScript<UILabel>("LvLb");
        Attribute_UISprite = root.FindScript<UISprite>("Attribute");
        Faction_UISprite = root.FindScript<UISprite>("Faction");

    }
    #endregion
}
