// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class BossBloodBar : BaseView
{
    public const string NAME ="BossBloodBar";

    #region Element Bindings

    /// bind gameobject
    public UILabel lblNum_UILabel;
    public UILabel lblPer_UILabel;
    public UISprite spNext_UISprite;
    public UISprite spStatus_UISprite;
    public UISprite spCur_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        lblNum_UILabel = root.FindScript<UILabel>("lblNum");
        lblPer_UILabel = root.FindScript<UILabel>("lblPer");
        spNext_UISprite = root.FindScript<UISprite>("spNext");
        spStatus_UISprite = root.FindScript<UISprite>("spStatus");
        spCur_UISprite = root.FindScript<UISprite>("spCur");

    }
    #endregion
}
