//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MultipleSelectionView.
/// </summary>
public partial class MultipleSelectionView : BaseView
{
	public UIAnchor viewAnchor;
	public UISprite ContentBg;
	public UIGrid btnGrid;
	public Transform btnGridTrans;
	public GameObject selectBtnPrefab;
	public UIPanel uiPanel;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
	viewAnchor = root.GetComponent<UIAnchor>();
		ContentBg = root.Find("ContentBg").GetComponent<UISprite>();
		btnGrid = root.Find("ContentBg/ButtonGrid").GetComponent<UIGrid>();
		btnGridTrans = root.Find("ContentBg/ButtonGrid");
		selectBtnPrefab = root.Find("ContentBg/ButtonGrid/selectBtnPrefab").gameObject;
	uiPanel = root.GetComponent<UIPanel>();
	}
}
