// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SkillEditorInfoItem : BaseView
{
    public const string NAME ="SkillEditorInfoItem";

    #region Element Bindings

    /// bind gameobject
    public UIButton SkillEditorInfoItem_UIButton;
    public UILabel Title_UILabel;
    public UIInput Value_UIInput;
    public BoxCollider Value_BoxCollider;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        SkillEditorInfoItem_UIButton = root.FindScript<UIButton>("");
        Title_UILabel = root.FindScript<UILabel>("Title");
        Value_UIInput = root.FindScript<UIInput>("Value");
        Value_BoxCollider = root.FindScript<BoxCollider>("Value");

    }
    #endregion
}
