// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SkillEditorTypeItem : BaseView
{
    public const string NAME ="SkillEditorTypeItem";

    #region Element Bindings

    /// bind gameobject
    public UIButton SkillEditorTypeItem_UIButton;
    public UISprite Sprite_UISprite;
    public UILabel Info_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        SkillEditorTypeItem_UIButton = root.FindScript<UIButton>("");
        Sprite_UISprite = root.FindScript<UISprite>("Sprite");
        Info_UILabel = root.FindScript<UILabel>("Info");

    }
    #endregion
}
