//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SkillEditorSaveAsView.
/// </summary>
public partial class SkillEditorSaveAsView : BaseView
{
	public const string NAME ="SkillEditorSaveAsView";
	public UIInput Id_UIInput;
	public UIInput Name_UIInput;
	public UIButton ConfirmBtn_UIButton;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		Id_UIInput = root.Find("Back/Id").GetComponent<UIInput>();
		Name_UIInput = root.Find("Back/Name").GetComponent<UIInput>();
		ConfirmBtn_UIButton = root.Find("Back/ConfirmBtn").GetComponent<UIButton>();
	}
}
