// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class SkillEditorNodeItem : BaseView
{
    public const string NAME ="SkillEditorNodeItem";

    #region Element Bindings

    /// bind gameobject
    public UIButton SkillEditorNodeItem_UIButton;
    public UISprite Sprite_UISprite;
    public UILabel Info_UILabel;
    public UISprite SkillEditorNodeItem_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        SkillEditorNodeItem_UIButton = root.FindScript<UIButton>("");
        Sprite_UISprite = root.FindScript<UISprite>("Sprite");
        Info_UILabel = root.FindScript<UILabel>("Info");
        SkillEditorNodeItem_UISprite = root.FindScript<UISprite>("");

    }
    #endregion
}
