// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  ScheduleProgRewardItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IScheduleProgRewardItemController
{
     UniRx.IObservable<Unit> OnIconBg_UIButtonClick{get;}

}

public partial class ScheduleProgRewardItemController:MonolessViewController<ScheduleProgRewardItem>, IScheduleProgRewardItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        IconBg_UIButtonEvt = View.IconBg_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        IconBg_UIButtonEvt = IconBg_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> IconBg_UIButtonEvt;
    public UniRx.IObservable<Unit> OnIconBg_UIButtonClick{
        get {return IconBg_UIButtonEvt;}
    }


}
