// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  ScheduleRewardTypeBtnController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IScheduleRewardTypeBtnController
{
     UniRx.IObservable<Unit> OnScheduleRewardTypeBtn_UIButtonClick{get;}

}

public partial class ScheduleRewardTypeBtnController:MonolessViewController<ScheduleRewardTypeBtn>, IScheduleRewardTypeBtnController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        ScheduleRewardTypeBtn_UIButtonEvt = View.ScheduleRewardTypeBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        ScheduleRewardTypeBtn_UIButtonEvt = ScheduleRewardTypeBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> ScheduleRewardTypeBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnScheduleRewardTypeBtn_UIButtonClick{
        get {return ScheduleRewardTypeBtn_UIButtonEvt;}
    }


}
