// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CharacterPropertyView : BaseView
{
    public const string NAME ="CharacterPropertyView";

    #region Element Bindings

    /// bind gameobject
    public UIButton PlayerIcon_UIButton;
    public UISprite PlayerIcon_UISprite;
    public UILabel Name_UILabel;
    public UILabel number_UILabel;
    public UILabel Lv_UILabel;
    public UIGrid BuffGroup_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        PlayerIcon_UIButton = root.FindScript<UIButton>("PlayerIcon");
        PlayerIcon_UISprite = root.FindScript<UISprite>("PlayerIcon/IconBg/PlayerIcon");
        Name_UILabel = root.FindScript<UILabel>("PlayerIcon/Name/Name");
        number_UILabel = root.FindScript<UILabel>("PlayerIcon/Power/number");
        Lv_UILabel = root.FindScript<UILabel>("PlayerIcon/Bg_lv/Lv");
        BuffGroup_UIGrid = root.FindScript<UIGrid>("BuffGroup");

    }
    #endregion
}
