// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class TeamSettingWinPrefab : BaseView
{
    public const string NAME ="TeamSettingWinPrefab";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UILabel TitleLb_UILabel;
    public UILabel DescLabel_UILabel;
    public UITable Table_UITable;
    public UIScrollView ScrollView_UIScrollView;
    public UIButton WinBg_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseWindow/CloseBtn");
        TitleLb_UILabel = root.FindScript<UILabel>("BaseWindow/TitleLb");
        DescLabel_UILabel = root.FindScript<UILabel>("MainContont/DescLabel");
        Table_UITable = root.FindScript<UITable>("MainContont/ScrollView/Table");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("MainContont/ScrollView");
        WinBg_UIButton = root.FindScript<UIButton>("BaseWindow/WinBg");

    }
    #endregion
}
