// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class TeamSetItem : BaseView
{
    public const string NAME ="TeamSetItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel NameLb_UILabel;
    public UILabel DescLb_UILabel;
    public UISprite Icon_UISprite;
    public UIButton Button_UIButton;
    public UISlider Slider_UISlider;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        NameLb_UILabel = root.FindScript<UILabel>("NameLb");
        DescLb_UILabel = root.FindScript<UILabel>("DescLb");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        Button_UIButton = root.FindScript<UIButton>("Button");
        Slider_UISlider = root.FindScript<UISlider>("Slider");

    }
    #endregion
}
