// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  AssistDelegateMainViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IAssistDelegateMainViewController
{
    UniRx.IObservable<Unit> OnUpdateMissionBtn_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCrewItem_1_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCrewItem_2_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCrewItem_3_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCrewItem_4_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCrewItem_5_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnCancelBtn_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnFastBtn_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnAcceptBtn_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnGetRewardBtn_UIButtonClick { get; }
    UniRx.IObservable<Unit> OnTipsBtn_UIButtonClick { get; }
}

public partial class AssistDelegateMainViewController:MonolessViewController<AssistDelegateMainView>, IAssistDelegateMainViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        UpdateMissionBtn_UIButtonEvt = View.UpdateMissionBtn_UIButton.AsObservable();
        CrewItem_1_UIButtonEvt = View.CrewItem_1_UIButton.AsObservable();
        CrewItem_2_UIButtonEvt = View.CrewItem_2_UIButton.AsObservable();
        CrewItem_3_UIButtonEvt = View.CrewItem_3_UIButton.AsObservable();
        CrewItem_4_UIButtonEvt = View.CrewItem_4_UIButton.AsObservable();
        CrewItem_5_UIButtonEvt = View.CrewItem_5_UIButton.AsObservable();
        CancelBtn_UIButtonEvt = View.CancelBtn_UIButton.AsObservable();
        FastBtn_UIButtonEvt = View.FastBtn_UIButton.AsObservable();
        AcceptBtn_UIButtonEvt = View.AcceptBtn_UIButton.AsObservable();
        GetRewardBtn_UIButtonEvt = View.GetRewardBtn_UIButton.AsObservable();
        TipsBtn_UIButtonEvt = View.TipsBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        UpdateMissionBtn_UIButtonEvt = UpdateMissionBtn_UIButtonEvt.CloseOnceNull();
        CrewItem_1_UIButtonEvt = CrewItem_1_UIButtonEvt.CloseOnceNull();
        CrewItem_2_UIButtonEvt = CrewItem_2_UIButtonEvt.CloseOnceNull();
        CrewItem_3_UIButtonEvt = CrewItem_3_UIButtonEvt.CloseOnceNull();
        CrewItem_4_UIButtonEvt = CrewItem_4_UIButtonEvt.CloseOnceNull();
        CrewItem_5_UIButtonEvt = CrewItem_5_UIButtonEvt.CloseOnceNull();
        CancelBtn_UIButtonEvt = CancelBtn_UIButtonEvt.CloseOnceNull();
        FastBtn_UIButtonEvt = FastBtn_UIButtonEvt.CloseOnceNull();
        AcceptBtn_UIButtonEvt = AcceptBtn_UIButtonEvt.CloseOnceNull();
        GetRewardBtn_UIButtonEvt = GetRewardBtn_UIButtonEvt.CloseOnceNull();
        TipsBtn_UIButtonEvt = TipsBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> UpdateMissionBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnUpdateMissionBtn_UIButtonClick{
        get {return UpdateMissionBtn_UIButtonEvt;}
    }

    private Subject<Unit> CrewItem_1_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCrewItem_1_UIButtonClick{
        get {return CrewItem_1_UIButtonEvt;}
    }

    private Subject<Unit> CrewItem_2_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCrewItem_2_UIButtonClick{
        get {return CrewItem_2_UIButtonEvt;}
    }

    private Subject<Unit> CrewItem_3_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCrewItem_3_UIButtonClick{
        get {return CrewItem_3_UIButtonEvt;}
    }

    private Subject<Unit> CrewItem_4_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCrewItem_4_UIButtonClick{
        get {return CrewItem_4_UIButtonEvt;}
    }

    private Subject<Unit> CrewItem_5_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCrewItem_5_UIButtonClick{
        get {return CrewItem_5_UIButtonEvt;}
    }

    private Subject<Unit> CancelBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCancelBtn_UIButtonClick{
        get {return CancelBtn_UIButtonEvt;}
    }

    private Subject<Unit> FastBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnFastBtn_UIButtonClick{
        get {return FastBtn_UIButtonEvt;}
    }
    
    private Subject<Unit> AcceptBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnAcceptBtn_UIButtonClick{
        get {return AcceptBtn_UIButtonEvt;}
    }
    
    private Subject<Unit> GetRewardBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnGetRewardBtn_UIButtonClick
    {
        get { return GetRewardBtn_UIButtonEvt; }
    }

    private Subject<Unit> TipsBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTipsBtn_UIButtonClick
    {
        get { return TipsBtn_UIButtonEvt; }
    }
}
