// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  AssistSkillForgetViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IAssistSkillForgetViewController
{

}

public partial class AssistSkillForgetViewController:MonolessViewController<AssistSkillForgetView>, IAssistSkillForgetViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
