//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleAutoSummonConfigView.
/// </summary>
public partial class BattleAutoSummonConfigView : BaseView
{
	public const string NAME ="BattleAutoSummonConfigView";
	public UIButton BtnClose_UIButton;
	public UIGrid GridCardList_UIGrid;
	public UIScrollView ScrollViewCardList_UIScrollView;
	public UIWidget CntrLvs_UIWidget;
	public Transform CntrLvs_Transform;
	public UIButton CurrentLv_UIButton;
	public GameObject CurrentUsedHero;
	public GameObject CurrentUsedHeroBG;
	public UIGrid GridCardPostionBG_UIGrid;
	public UIGrid GridCardPostion_UIGrid;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		BtnClose_UIButton = root.Find("CntrMain/CntrBG/BtnClose").GetComponent<UIButton>();
		GridCardList_UIGrid = root.Find("CntrMain/CntrCards/CntrCardList/DragClipCntr/ScrollViewCardList/GridCardList").GetComponent<UIGrid>();
		ScrollViewCardList_UIScrollView = root.Find("CntrMain/CntrCards/CntrCardList/DragClipCntr/ScrollViewCardList").GetComponent<UIScrollView>();
		CntrLvs_UIWidget = root.Find("CntrMain/CntrCards/CntrCardList/CntrLevels/CntrLvs").GetComponent<UIWidget>();
		CntrLvs_Transform = root.Find("CntrMain/CntrCards/CntrCardList/CntrLevels/CntrLvs");
		CurrentLv_UIButton = root.Find("CntrMain/CntrCards/CntrCardList/CntrLevels/CurrentLv").GetComponent<UIButton>();
		CurrentUsedHero = root.Find("CntrMain/CntrCards/CntrCurrent/CurrentUsedHero").gameObject;
		CurrentUsedHeroBG = root.Find("CntrMain/CntrCardBG/CntrCurrent/CurrentUsedHeroBG").gameObject;
		GridCardPostionBG_UIGrid = root.Find("CntrMain/CntrCardBG/CntrCardPostion/GridCardPostionBG").GetComponent<UIGrid>();
		GridCardPostion_UIGrid = root.Find("CntrMain/CntrCards/CntrCardPostion/GridCardPostion").GetComponent<UIGrid>();
	}
}
