//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for HeroCardItem.
/// </summary>
public partial class HeroCardItem : BaseView
{
	public const string NAME ="HeroCardItem";
	public UIButton HeroCardItem_UIButton;
	public UISprite SpriteSelected_UISprite;
	public UIDragScrollView HeroCardItem_UIDragScrollView;
	public UILabel LabelLv_UILabel;
	public UILabel LabelName_UILabel;
	public UISprite SpriteCountry_UISprite;
	public UISprite HeadIcon_UISprite;
	public UISprite HeroCardItem_UISprite;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
	HeroCardItem_UIButton = root.GetComponent<UIButton>();
		SpriteSelected_UISprite = root.Find("CntrMain/SpriteSelected").GetComponent<UISprite>();
	HeroCardItem_UIDragScrollView = root.GetComponent<UIDragScrollView>();
		LabelLv_UILabel = root.Find("CntrMain/LabelLv").GetComponent<UILabel>();
		LabelName_UILabel = root.Find("CntrMain/LabelName").GetComponent<UILabel>();
		SpriteCountry_UISprite = root.Find("CntrMain/SpriteCountry").GetComponent<UISprite>();
		HeadIcon_UISprite = root.Find("CntrMain/HeadIcon").GetComponent<UISprite>();
	HeroCardItem_UISprite = root.GetComponent<UISprite>();
	}
}
