// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  SearchFriendItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ISearchFriendItemController
{
     UniRx.IObservable<Unit> OnFriendIcon_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnAddBtn_UIButtonClick{get;}

}

public partial class SearchFriendItemController:MonolessViewController<SearchFriendItem>, ISearchFriendItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        FriendIcon_UIButtonEvt = View.FriendIcon_UIButton.AsObservable();
        AddBtn_UIButtonEvt = View.AddBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        FriendIcon_UIButtonEvt = FriendIcon_UIButtonEvt.CloseOnceNull();
        AddBtn_UIButtonEvt = AddBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> FriendIcon_UIButtonEvt;
    public UniRx.IObservable<Unit> OnFriendIcon_UIButtonClick{
        get {return FriendIcon_UIButtonEvt;}
    }

    private Subject<Unit> AddBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnAddBtn_UIButtonClick{
        get {return AddBtn_UIButtonEvt;}
    }


}
