// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuildEventView : BaseView
{
    public const string NAME ="GuildEventView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UIScrollView ScrollView_UIScrollView;
    public UIRecycledList MessageContent_UIRecycledList;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("ScrollView");
        MessageContent_UIRecycledList = root.FindScript<UIRecycledList>("ScrollView/MessageContent");

    }
    #endregion
}
