// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class NoticeModificationView : BaseView
{
    public const string NAME ="NoticeModificationView";

    #region Element Bindings

    /// bind gameobject
    public UILabel TitleLabel_UILabel;
    public UIButton CloseBtn_UIButton;
    public UIButton PublishBtn_UIButton;
    public UIInput TextInput_UIInput;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TitleLabel_UILabel = root.FindScript<UILabel>("TitleLabel");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        PublishBtn_UIButton = root.FindScript<UIButton>("PublishBtn");
        TextInput_UIInput = root.FindScript<UIInput>("TextInput");

    }
    #endregion
}
