// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewCraftSkillViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ICrewCraftSkillViewController
{
     UniRx.IObservable<Unit> OnSkillUpgradeBtn_UIButtonClick{get;}

}

public partial class CrewCraftSkillViewController:MonolessViewController<CrewCraftSkillView>, ICrewCraftSkillViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        SkillUpgradeBtn_UIButtonEvt = View.SkillUpgradeBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        SkillUpgradeBtn_UIButtonEvt = SkillUpgradeBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> SkillUpgradeBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnSkillUpgradeBtn_UIButtonClick{
        get {return SkillUpgradeBtn_UIButtonEvt;}
    }


}
