// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewSkillViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial interface ICrewSkillViewController
{
}

public partial class CrewSkillViewController:MonolessViewController<CrewSkillView>, ICrewSkillViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
