//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleSummonPetCell.
/// </summary>
public partial class BattleSummonPetCell : BaseView
{
    public const string NAME ="BattleSummonPetCell";
    public UISprite ItemIcon_UISprite;
    public UISprite StatusSprite_UISprite;
    public UILabel NameLabel_UILabel;
    public UILabel InfoLabel_UILabel;
    public UISprite CellSelectSprite_UISprite;
    public UIButton BattleSummonPetCell_UIButton;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
        ItemIcon_UISprite = root.Find("ItemCell/ItemIcon").GetComponent<UISprite>();
        StatusSprite_UISprite = root.Find("ItemCell/StatusSprite").GetComponent<UISprite>();
        NameLabel_UILabel = root.Find("NameLabel").GetComponent<UILabel>();
        InfoLabel_UILabel = root.Find("InfoLabel").GetComponent<UILabel>();
        CellSelectSprite_UISprite = root.Find("CellSelectSprite").GetComponent<UISprite>();
        BattleSummonPetCell_UIButton = root.GetComponent<UIButton>();
    }
}
