// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  PreviewHeadController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IPreviewHeadController
{

}

public partial class PreviewHeadController:MonolessViewController<PreviewHead>, IPreviewHeadController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
