// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  AssistProductItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IAssistProductItemController
{
     UniRx.IObservable<Unit> OnAssistProductItem_UIButtonClick{get;}

}

public partial class AssistProductItemController:MonolessViewController<AssistProductItem>, IAssistProductItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        AssistProductItem_UIButtonEvt = View.AssistProductItem_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        AssistProductItem_UIButtonEvt = AssistProductItem_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> AssistProductItem_UIButtonEvt;
    public UniRx.IObservable<Unit> OnAssistProductItem_UIButtonClick{
        get {return AssistProductItem_UIButtonEvt;}
    }


}
