// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class RoleSkillMagicItem : BaseView
{
    public const string NAME ="RoleSkillMagicItem";

    #region Element Bindings

    /// bind gameobject
    public UITexture spIcon_UISprite;
    public UISprite spLock_UISprite;
    public UISprite spAdd_UISprite;
    public UISprite spSelected_UISprite;
    public UILabel lblName_UILabel;
    public UISprite lblBG_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        spIcon_UISprite = root.FindScript<UITexture>("spIcon");
        spLock_UISprite = root.FindScript<UISprite>("spLock");
        spAdd_UISprite = root.FindScript<UISprite>("spAdd");
        spSelected_UISprite = root.FindScript<UISprite>("spSelected");
        lblName_UILabel = root.FindScript<UILabel>("lblName");
        lblBG_UISprite = root.FindScript<UISprite>("lblName/lblBG");

    }
    #endregion
}
