// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class RoleSkillMainView : BaseView
{
    public const string NAME ="RoleSkillMainView";

    #region Element Bindings

    /// bind gameobject
    public UIGrid tabBtn_UIGrid;
    public Transform Content_Transform;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        tabBtn_UIGrid = root.FindScript<UIGrid>("Content/tabBtn");
        Content_Transform = root.FindTrans("Content");

    }
    #endregion
}
