// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  FormationDebuffItemController.cs
// the file is generated by tools
// **********************************************************************

public partial class FormationDebuffItemController:MonolessViewController<FormationDebuffItem>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
