// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class EngraveView : BaseView
{
    public const string NAME ="EngraveView";

    #region Element Bindings

    /// bind gameobject
    public UITable LeftTable_UITable;
    public UIButton SaleBtn_UIButton;
    public UITable RightTable_UITable;
    public UIButton EngraveBtn_UIButton;
    public UISlider CapacitySlider_UISlider;
    public UILabel PercentLabel_UILabel;
    public UIButton TipBtn_UIButton;
    public UILabel EmptyTips_UILabel;
    public UIButton CloseBtn_UIButton;
    public UIScrollView Left_UIScrollView;
    public UIScrollView Right_UIScrollView;
    public GameObject MiddlePanel;
    public GameObject HoleAnchor;
    public GameObject AttrContent;
    public UIGrid AttrContent_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        LeftTable_UITable = root.FindScript<UITable>("LeftPanel/ScrollView/LeftTable");
        SaleBtn_UIButton = root.FindScript<UIButton>("LeftPanel/SaleBtn");
        RightTable_UITable = root.FindScript<UITable>("RightPanel/ScrollView/RightTable");
        EngraveBtn_UIButton = root.FindScript<UIButton>("RightPanel/EngraveBtn");
        CapacitySlider_UISlider = root.FindScript<UISlider>("MiddlePanel/CapacitySlider");
        PercentLabel_UILabel = root.FindScript<UILabel>("MiddlePanel/CapacitySlider/PercentLabel");
        TipBtn_UIButton = root.FindScript<UIButton>("RightPanel/TipBtn");
        EmptyTips_UILabel = root.FindScript<UILabel>("MiddlePanel/EmptyTips");
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseMainWindow/CloseBtn");
        Left_UIScrollView = root.FindScript<UIScrollView>("LeftPanel/ScrollView");
        Right_UIScrollView = root.FindScript<UIScrollView>("RightPanel/ScrollView");
        MiddlePanel = root.FindGameObject("MiddlePanel");
        HoleAnchor = root.FindGameObject("HoleAnchor");
        AttrContent = root.FindGameObject("MiddlePanel/AttrContent");
        AttrContent_UIGrid = root.FindScript<UIGrid>("MiddlePanel/AttrContent");

    }
    #endregion
}
