// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EmailViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IEmailViewController
{
     UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnGetBtn_UIButtonClick{get;}

}

public partial class EmailViewController:MonolessViewController<EmailView>, IEmailViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        CloseBtn_UIButtonEvt = View.CloseBtn_UIButton.AsObservable();
        GetBtn_UIButtonEvt = View.GetBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        CloseBtn_UIButtonEvt = CloseBtn_UIButtonEvt.CloseOnceNull();
        GetBtn_UIButtonEvt = GetBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> CloseBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnCloseBtn_UIButtonClick{
        get {return CloseBtn_UIButtonEvt;}
    }

    private Subject<Unit> GetBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnGetBtn_UIButtonClick{
        get {return GetBtn_UIButtonEvt;}
    }


}
