// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  EmailAttatchItemController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class EmailAttatchItemController:MonolessViewController<EmailAttatchItem>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
