//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class ChatSystemItem : BaseView
{
    public const string NAME ="ChatSystemItem";

    #region Element Bindings

    /// bind gameobject
        public GameObject content;
    public EmojiAnimationController content_UILabel;
    public UIEventListener eventListener;
    public BoxCollider content_BocCollider;

    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
                content = root.FindGameObject("content");
        content_UILabel = root.FindScript<EmojiAnimationController>("content");
        eventListener = root.FindScript<UIEventListener>("content");
        content_BocCollider = root.FindScript<BoxCollider>("content");
    }
    #endregion
}

