// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class RightExpandBtnGroup : BaseView
{
    public const string NAME ="RightExpandBtnGroup";

    #region Element Bindings

    /// bind gameobject
    public TweenPosition RightExpandBtnGroup_TweenPosition;
    public UIGrid Grid_UIGrid;
    public UISprite BackGround_UISprite;
    public UISprite BackGround_1_UISprite;
    public UIButton PullBtn_UIButton;
    public UISprite PullBtn_Sprite;
    public UIButton Button_Ranking_UIButton;
    public UIButton Button_Trade_UIButton;
    public UIButton Button_Equip_UIButton;
    public UIButton Button_Store_UIButton;
    public UIButton Button_CardBtn_UIButton;
    public UIButton Button_UpBtn_UIButton;
    public UIButton Button_FirstBtn_UIButton;
    public UIButton Button_GuideBtn_UIButton;
    public UIButton Button_WelfareBtn_UIButton;
    public UIButton Button_Daily_UIButton;
    public UIButton Button_Skill_UIButton;
    public UIButton Button_Pack_UIButton;
    public UIButton Button_Guild_UIButton;
    public UIButton Button_TempBtn_UIButton;
    public UIButton Button_Crew_UIButton;
    public UIButton Button_Recruit_UIButton;
    public UIButton Button_AttackMan_UIButton;
    public UIButton Button_Quartz_UIButton;
    public UIButton Button_Faction_UIButton;
    public UIButton Button_Collect_UIButton;
    public UIButton Button_Achievement_UIButton;
    public UIButton Button_lifeskill_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        RightExpandBtnGroup_TweenPosition = root.FindScript<TweenPosition>("");
        Grid_UIGrid = root.FindScript<UIGrid>("Grid");
        BackGround_UISprite = root.FindScript<UISprite>("BackGround");
        BackGround_1_UISprite = root.FindScript<UISprite>("BackGround/BackGround_1");
        PullBtn_UIButton = root.FindScript<UIButton>("BackGround/PullBtn");
        PullBtn_Sprite = root.FindScript<UISprite>("BackGround/PullBtn");
        Button_Ranking_UIButton = root.FindScript<UIButton>("Grid/Button_Ranking");
        Button_Trade_UIButton = root.FindScript<UIButton>("Grid/Button_Trade");
        Button_Equip_UIButton = root.FindScript<UIButton>("Grid/Button_Equip");
        Button_Store_UIButton = root.FindScript<UIButton>("Grid/Button_Store");
        Button_CardBtn_UIButton = root.FindScript<UIButton>("Grid/Button_CardBtn");
        Button_UpBtn_UIButton = root.FindScript<UIButton>("Grid/Button_UpBtn");
        Button_FirstBtn_UIButton = root.FindScript<UIButton>("Grid/Button_FirstBtn");
        Button_GuideBtn_UIButton = root.FindScript<UIButton>("Grid/Button_GuideBtn");
        Button_WelfareBtn_UIButton = root.FindScript<UIButton>("Grid/Button_WelfareBtn");
        Button_Daily_UIButton = root.FindScript<UIButton>("Grid/Button_Daily");
        Button_Skill_UIButton = root.FindScript<UIButton>("Grid/Button_Skill");
        Button_Pack_UIButton = root.FindScript<UIButton>("Grid/Button_Pack");
        Button_Guild_UIButton = root.FindScript<UIButton>("Grid/Button_Guild");
        Button_TempBtn_UIButton = root.FindScript<UIButton>("Grid/Button_TempBtn");
        Button_Crew_UIButton = root.FindScript<UIButton>("Grid/Button_Crew");
        Button_Recruit_UIButton = root.FindScript<UIButton>("Grid/Button_Recruit");
        Button_AttackMan_UIButton = root.FindScript<UIButton>("Grid/Button_AttackMan");
        Button_Quartz_UIButton = root.FindScript<UIButton>("Grid/Button_Quartz");
        Button_Faction_UIButton = root.FindScript<UIButton>("Grid/Button_Faction");
        Button_Collect_UIButton = root.FindScript<UIButton>("Grid/Button_Collect");
        Button_Achievement_UIButton = root.FindScript<UIButton>("Grid/Button_Achievement");
        Button_lifeskill_UIButton = root.FindScript<UIButton>("Grid/Button_lifeskill");

    }
    #endregion
}
