// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class NpcDialogueView : BaseView
{
    public const string NAME ="NpcDialogueView";

    #region Element Bindings

    /// bind gameobject
    public GameObject OptionBg;
    public UIButton ClickBtnBoxCollider_UIButton;
    public UILabel NameLabel_UILabel;
    public UILabel MsgLabel_UILabel;
    public GameObject FunctionCell;
    public UIGrid FunctionGrid_UIGrid;
    public GameObject UIAnchorPosition;
    public UITexture FaceTexture;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        OptionBg = root.FindGameObject("ContentGroup/OptionBg");
        ClickBtnBoxCollider_UIButton = root.FindScript<UIButton>("ClickBtnBoxCollider");
        NameLabel_UILabel = root.FindScript<UILabel>("ContentGroup/NameBg/NameLabel");
        MsgLabel_UILabel = root.FindScript<UILabel>("ContentGroup/MsgLabel");
        FunctionCell = root.FindGameObject("ContentGroup/OptionBg/FunctionGrid/FunctionCell");
        FunctionGrid_UIGrid = root.FindScript<UIGrid>("ContentGroup/OptionBg/FunctionGrid");
        UIAnchorPosition = root.FindGameObject("ContentGroup/UIAnchor");
        FaceTexture = root.FindScript<UITexture>("ContentGroup/FaceTexture");
    }
    #endregion
}
