// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class GoodsTipsSpriteItem : BaseView
{
    public const string NAME ="GoodsTipsSpriteItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite ItemIcon_UISprite;
    public UISprite Bg_UISprite;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ItemIcon_UISprite = root.FindScript<UISprite>("ItemIcon");
        Bg_UISprite = root.FindScript<UISprite>("Bg");
    }
    #endregion
}
