// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class GoodsTipsTitleView : BaseView
{
    public const string NAME ="GoodsTipsTitleView";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UISprite Quality_UISprite;
    public UISprite GrayMask_UISprite;
    public UILabel Name_UILabel;
    public UILabel Lv_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("ItemCell/Icon");
        Quality_UISprite = root.FindScript<UISprite>("ItemCell/Quality");
        GrayMask_UISprite = root.FindScript<UISprite>("ItemCell/GrayMask");
        Name_UILabel = root.FindScript<UILabel>("Name");
        Lv_UILabel = root.FindScript<UILabel>("Lv");

    }
    #endregion
}
