// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class GoodsTipsLine : BaseView
{
    public const string NAME ="GoodsTipsLine";

    #region Element Bindings

    /// bind gameobject


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;

    }
    #endregion
}
