// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BracerLvUpView : BaseView
{
    public const string NAME ="BracerLvUpView";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UISprite Bg_UISprite;
    public UISprite ShadowBg_UISprite;
    public UIScrollView ScrollView_UIScrollView;
    public UIGrid Grid_UIGrid;
    public UILabel LvName_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        Bg_UISprite = root.FindScript<UISprite>("Bg");
        ShadowBg_UISprite = root.FindScript<UISprite>("ShadowBg");
        LvName_UILabel = root.FindScript<UILabel>("LvName");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("InfoBg/ScrollView");
        Grid_UIGrid = root.FindScript<UIGrid>("InfoBg/ScrollView/Grid");

    }
    #endregion
}
