// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class BracerLvUpItem : BaseView
{
    public const string NAME ="BracerLvUpItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel Label_UILabel;
    public UISprite Icon_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Label_UILabel = root.FindScript<UILabel>("Label");
        Icon_UISprite = root.FindScript<UISprite>("Icon");

    }
    #endregion
}
