// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  MissionTypeItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IMissionTypeItemController
{
    UniRx.IObservable<Unit> MissionTypeItem_UIButtonClick { get; }
}

public partial class MissionTypeItemController:MonolessViewController<MissionTypeItem>, IMissionTypeItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        MissionTypeItem_UIButtonEvt = View.MissionTypeItem_UIButton.AsObservable();
    }

    protected override void ClearReactiveEvents(){
        MissionTypeItem_UIButtonEvt = MissionTypeItem_UIButtonEvt.CloseOnceNull();
    }

    private Subject<Unit> MissionTypeItem_UIButtonEvt;
    public UniRx.IObservable<Unit> MissionTypeItem_UIButtonClick
    {
        get { return MissionTypeItem_UIButtonEvt; }
    }
}
