// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RecordEvtItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IRecordEvtItemController
{
     UniRx.IObservable<Unit> OnRecordEvtItem_UIButtonClick{get;}

}

public partial class RecordEvtItemController:MonolessViewController<RecordEvtItem>, IRecordEvtItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        RecordEvtItem_UIButtonEvt = View.RecordEvtItem_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        RecordEvtItem_UIButtonEvt = RecordEvtItem_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> RecordEvtItem_UIButtonEvt;
    public UniRx.IObservable<Unit> OnRecordEvtItem_UIButtonClick{
        get {return RecordEvtItem_UIButtonEvt;}
    }


}
