// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  SubMissionItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ISubMissionItemController
{
     UniRx.IObservable<Unit> OnSubMissionItem_UIButtonClick{get;}

}

public partial class SubMissionItemController:MonolessViewController<SubMissionItem>, ISubMissionItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        SubMissionItem_UIButtonEvt = View.SubMissionItem_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        SubMissionItem_UIButtonEvt = SubMissionItem_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> SubMissionItem_UIButtonEvt;
    public UniRx.IObservable<Unit> OnSubMissionItem_UIButtonClick{
        get {return SubMissionItem_UIButtonEvt;}
    }


}
