// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  TipsLabelItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ITipsLabelItemController
{

}

public partial class TipsLabelItemController:MonolessViewController<TipsLabelItem>, ITipsLabelItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
