// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  TipsLabAndSprViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ITipsLabAndSprViewController
{

}

public partial class TipsLabAndSprViewController:MonolessViewController<TipsLabAndSprView>, ITipsLabAndSprViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
