// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  TipsEquipmentGroupAttrItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ITipsEquipmentGroupAttrItemController
{

}

public partial class TipsEquipmentGroupAttrItemController:MonolessViewController<TipsEquipmentGroupAttrItem>, ITipsEquipmentGroupAttrItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){

    }

    protected override void ClearReactiveEvents(){

    }


}
