// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuideMainView : BaseView
{
    public const string NAME ="GuideMainView";

    #region Element Bindings

    /// bind gameobject
    public UIScrollView ScrollView_UIScrollView;
    public UIGrid Grid_UIGrid;
    public UIButton CloseBtn_UIButton;
    public GameObject EmptyPanel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("Panel/ScrollView");
        Grid_UIGrid = root.FindScript<UIGrid>("Panel/ScrollView/Grid");
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        EmptyPanel = root.FindGameObject("EmptyPanel");

    }
    #endregion
}
