// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  BuffShowItemController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial class BuffShowItemController:MonolessViewController<BuffShowItem>, IBuffShowItemController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        BuffShowItem_UIButtonEvt = View.BuffShowItem_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        BuffShowItem_UIButtonEvt = BuffShowItem_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> BuffShowItem_UIButtonEvt;
    public UniRx.IObservable<Unit> OnBuffShowItem_UIButtonClick{
        get {return BuffShowItem_UIButtonEvt;}
    }


}
