// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  RecommendTeamViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class RecommendTeamViewController:MonolessViewController<RecommendTeamView>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        OneKeyInviteBtn_UIButtonEvt = View.OneKeyInviteBtn_UIButton.AsObservable();
        RefreshBtn_UIButtonEvt = View.RefreshBtn_UIButton.AsObservable();
        OneKeyApplyBtn_UIBUttonEvt = View.OneKeyApplyBtn_UIButton.AsObservable();
    }

    protected override void ClearReactiveEvents(){
        OneKeyInviteBtn_UIButtonEvt = OneKeyInviteBtn_UIButtonEvt.CloseOnceNull();
        RefreshBtn_UIButtonEvt = RefreshBtn_UIButtonEvt.CloseOnceNull();
        OneKeyApplyBtn_UIBUttonEvt = OneKeyApplyBtn_UIBUttonEvt.CloseOnceNull();
    }

    private Subject<Unit> OneKeyInviteBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnOneKeyInviteBtn_UIButtonClick{
        get {return OneKeyInviteBtn_UIButtonEvt;}
    }

    private Subject<Unit> RefreshBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnRefreshBtn_UIButtonClick{
        get {return RefreshBtn_UIButtonEvt;}
    }

    private Subject<Unit> OneKeyApplyBtn_UIBUttonEvt;
    public UniRx.IObservable<Unit> OneKeyApplyBtn_UIButtonClick
    {
        get { return OneKeyApplyBtn_UIBUttonEvt; }
    }
}
