// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  TeamApplicationItemController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class TeamApplicationItemController:MonolessViewController<TeamApplicationItem>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        agreeBtn_UIButtonEvt = View.agreeBtn_UIButton.AsObservable();
    }

    protected override void ClearReactiveEvents(){
        TeamApplicationItem_UIButtonEvt = TeamApplicationItem_UIButtonEvt.CloseOnceNull();
        agreeBtn_UIButtonEvt = agreeBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> TeamApplicationItem_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTeamApplicationItem_UIButtonClick{
        get {return TeamApplicationItem_UIButtonEvt;}
    }

    private Subject<Unit> agreeBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnagreeBtn_UIButtonClick{
        get {return agreeBtn_UIButtonEvt;}
    }


}
