// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class ChatFriendItem : BaseView
{
    public const string NAME ="ChatFriendItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UILabel Name_UILabel;
    public UILabel Lv_UILabel;
    public UIButton Bg_UIButton;
    public UISprite RedPot_UISprite;
    public UISprite ChoseBg_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        Name_UILabel = root.FindScript<UILabel>("Name");
        Lv_UILabel = root.FindScript<UILabel>("Lv");
        Bg_UIButton = root.FindScript<UIButton>("Bg");
        RedPot_UISprite = root.FindScript<UISprite>("RedPot");
        ChoseBg_UISprite = root.FindScript<UISprite>("ChoseBg");

    }
    #endregion
}
