// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class PrivateMsgView : BaseView
{
    public const string NAME ="PrivateMsgView";

    #region Element Bindings

    /// bind gameobject
    public UIScrollView LeftScrollView_UIScrollView;
    public UIGrid LeftGird_UIGrid;
    public UIScrollView RightScrollView_UIScrollView;
    public UITable RightTable_UITable;
    public UIButton Icon_UIButton;
    public UILabel Label_UILabel;
    public UIButton DeleteBtn_UIButton;
    public UIButton SpeedOrInputBtn_UIButton;
    public UIButton Expression_UIButton;
    public UIInput Input_UIInput;
    public UIEventListener SpeechBtn_UIEventListener;
    public UIButton SendBtn_UIButton;
    public GameObject FaceAnchor;
    public GameObject Degree;
    public UIPanel UnReadPanel_UIPanel;
    public UIButton UnReadBtn_UIButton;
    public UILabel UnReadCountLbl_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        LeftScrollView_UIScrollView = root.FindScript<UIScrollView>("LeftScrollView");
        LeftGird_UIGrid = root.FindScript<UIGrid>("LeftScrollView/LeftGird");
        RightScrollView_UIScrollView = root.FindScript<UIScrollView>("RightScrollView");
        RightTable_UITable = root.FindScript<UITable>("RightScrollView/RightTable");
        Icon_UIButton = root.FindScript<UIButton>("Degree/Icon");
        Label_UILabel = root.FindScript<UILabel>("Degree/DegreeLabel");
        DeleteBtn_UIButton = root.FindScript<UIButton>("Degree/DeleteBtn");
        SpeedOrInputBtn_UIButton = root.FindScript<UIButton>("ChatInputGroup/SpeedOrInputBtn");
        Expression_UIButton = root.FindScript<UIButton>("ChatInputGroup/Expression");
        Input_UIInput = root.FindScript<UIInput>("ChatInputGroup/Input");
        SpeechBtn_UIEventListener = root.FindScript<UIEventListener>("ChatInputGroup/SpeechBtn");
        SendBtn_UIButton = root.FindScript<UIButton>("ChatInputGroup/SendBtn");
        FaceAnchor = root.FindGameObject("FaceAnchor");
        Degree = root.FindGameObject("Degree");
        UnReadPanel_UIPanel = root.FindScript<UIPanel>("UnReadPanel");
        UnReadBtn_UIButton = root.FindScript<UIButton>("UnReadPanel/UnReadBtn");
        UnReadCountLbl_UILabel = root.FindScript<UILabel>("UnReadPanel/UnReadBtn/UnReadCountLbl");

    }
    #endregion
}
