// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewFetterViewController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class CrewFetterViewController:MonolessViewController<CrewFetterView>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        activateBtn_UIButtonEvt = View.activateBtn_UIButton.AsObservable();
        CrewFetterTipBtn_UIButtonEvt = View.CrewFetterTipBtn_UIButton.AsObservable();


    }

    protected override void ClearReactiveEvents(){
        activateBtn_UIButtonEvt = activateBtn_UIButtonEvt.CloseOnceNull();
        CrewFetterTipBtn_UIButtonEvt = CrewFetterTipBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> activateBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnactivateBtn_UIButtonClick{
        get {return activateBtn_UIButtonEvt;}
    }

    private Subject<Unit> CrewFetterTipBtn_UIButtonEvt;

    public UniRx.IObservable<Unit> OnCrewFetterTipBtn_UIButtonlick {
        get { return CrewFetterTipBtn_UIButtonEvt; }
    }

}
