// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  CrewFetterItemController.cs
// the file is generated by tools
// **********************************************************************

using System;
using UniRx;

public partial class CrewFetterItemController:MonolessViewController<CrewFetterItem>
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        RelateParners_UIButtonEvt = View.RelateParners_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        RelateParners_UIButtonEvt = RelateParners_UIButtonEvt.CloseOnceNull();
    }

    private Subject<Unit> RelateParners_UIButtonEvt;
    public UniRx.IObservable<Unit> OnRelateParners_UIButtonClick{
        get {return RelateParners_UIButtonEvt;}
    }


}
