//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class EmojiItemCell : BaseView
{
    public const string NAME ="EmojiItemCell";

    #region Element Bindings

    /// bind gameobject
    

    protected override void InitElementBinding ()
    {
	var root = this.gameObject;
        
    }
    #endregion
}

