//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class MsgRecordItemCell : BaseView
{
    public const string NAME ="MsgRecordItemCell";

    #region Element Bindings

    /// bind gameobject
        public UILabel MsgLbl_UILabel;
    public UISprite Content_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        MsgLbl_UILabel = root.FindScript<UILabel>("Content/MsgLbl");
        Content_UISprite = root.FindScript<UISprite>("Content");
    }
    #endregion
}

