// **********************************************************************
// Copyright (c) 2016 Baoyugame. All rights reserved.
// Author : Xianjian
// Created : 9/29/2016 4:44:19 PM
// Desc	: Auto generated by MarsZ. update this if need.
// **********************************************************************

using UnityEngine;
using SdkAccountDto;

 /// <summary>
 /// This is the controller class for module PlatformLogin, use this to control the ui or view , such as it's init , update or dispose.
 /// @Xianjian in 9/29/2016 4:44:19 PM
 /// </summary>
public class SdkPlatformLoginController : MonoViewController<SdkPlatformLoginView>
{
    protected override void RegistCustomEvent()
    {
        EventDelegate.Set(_view.BackBtn.onClick, () => { SdkProxyModule.CloseModuleSlow(SdkPlatformLoginView.NAME); });
        EventDelegate.Set(_view.RegisterBtn.onClick, OnRegister);
        EventDelegate.Set(_view.EnterBtn.onClick, OnEnterGame);
        EventDelegate.Set(_view.FindpasswordBtn.onClick, OnFindPassword);
    }

    public void OnFindPassword()
    {
        SdkProxyModule.OpenModule<SdkFindPasswordController>(SdkFindPasswordView.NAME);
    }

    public void OnRegister()
    {
        SdkProxyModule.OpenModule<SdkPlatformRegisterController>(SdkPlatformRegisterView.NAME);
    }

    public void OnEnterGame()
    {
        string account = _view.AccoutInput.value;
        string password = _view.PasswordInput.value;
        if(string.IsNullOrEmpty(account) || string.IsNullOrEmpty(password))
        {
            SdkProxyModule.ShowTips("账号或密码为空");
            return;
        }
        password = MD5Hashing.HashString(password);
        SdkAccountModel.Instance.DoLogin(account, password, AccountDto.AccountType.phone);
    }
}
