//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AccountQuickLoginView.
/// </summary>
public partial class SdkQuickLoginView : BaseView
{
	public const string NAME ="SdkQuickLoginView";
	public UIButton LoginBtn;
	public UIButton LastAccountBtn;
	public UIButton PlatformBtn;
	public UIButton TencentBtn;
	public UIGrid AccountGrid;
	public UISprite LastIcon;
	public UILabel LastLabel;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		LoginBtn = root.Find("LoginButton").GetComponent<UIButton>();
		LastAccountBtn = root.Find("LastAccount").GetComponent<UIButton>();
		PlatformBtn = root.Find("PlatformBtn").GetComponent<UIButton>();
		TencentBtn = root.Find("TencentBtn").GetComponent<UIButton>();
		AccountGrid = root.Find("AccountGrid").GetComponent<UIGrid>();
		LastIcon = root.Find("LastAccount/LastIcon").GetComponent<UISprite>();
		LastLabel = root.Find("LastAccount/LastLabel").GetComponent<UILabel>();
	}
}
