//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SelectLoginView.
/// </summary>
public partial class SdkSelectLoginView : BaseView
{
    public const string NAME = "SdkSelectLoginView";
	public UIButton QuickLoginBtn;
	public UIButton PlatformLoginBtn;
	public UIButton QQLoginBtn;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		QuickLoginBtn = root.Find("QuickLogin").GetComponent<UIButton>();
		PlatformLoginBtn = root.Find("PlatformLogin").GetComponent<UIButton>();
		QQLoginBtn = root.Find("QQLogin").GetComponent<UIButton>();
	}
}
