//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for _ModuleName_View.
/// </summary>
public partial class FriendView : BaseView
{
    public const string NAME ="FriendView";

    #region Element Bindings

    /// bind gameobject
    public UITable LeftTable_UITable;
    public UIScrollView RightScrollView_UIScrollView;
    public UITable ItemTable_UITable;
    public UIButton PersionHome_UIButton;
    public UILabel FriendLabel_UILabel;
    public UILabel Label_UILabel;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject;
        LeftTable_UITable = root.FindScript<UITable>("LeftTable");
        RightScrollView_UIScrollView = root.FindScript<UIScrollView>("RightScrollView");
        ItemTable_UITable = root.FindScript<UITable>("RightScrollView/ItemTable");
        PersionHome_UIButton = root.FindScript<UIButton>("PersionHome");
        FriendLabel_UILabel = root.FindScript<UILabel>("Label/FriendLabel");
        Label_UILabel = root.FindScript<UILabel>("Label");
    }
    #endregion
}

