//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for DistrictBtn.
/// </summary>
public partial class DistrictBtn : BaseView
{
	public UILabel NameLbl_UILabel;
	public UISprite RedPoint_UISprite;
	public UIButton DistrictBtn_UIButton;
	public UISprite Bg_UISprite;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		NameLbl_UILabel = root.Find("NameLbl").GetComponent<UILabel>();
		RedPoint_UISprite = root.Find("RedPoint").GetComponent<UISprite>();
	DistrictBtn_UIButton = root.GetComponent<UIButton>();
		Bg_UISprite = root.GetComponent<UISprite>();
	}
}
