//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ServerRoleBar.
/// </summary>
public partial class ServerRoleBar : BaseView
{
	public UIGrid RoleListGrid_UIGrid;
	public Transform ArrowSprite_Transform;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		RoleListGrid_UIGrid = root.Find("RoleListGrid").GetComponent<UIGrid>();
		ArrowSprite_Transform = root.Find("ArrowSprite");
	}
}
