// **********************************************************************
// Copyright (c) 2016 Baoyugame. All rights reserved.
// Author : MarsZ
// Created : 04/20/2017 16:20:24
// Desc	: Auto generated by MarsZ. update this if need.
// **********************************************************************

using UnityEngine;
 /// <summary>
 /// This is the proxy class for module BattleFightPreview, use this to show or hide this module.
 /// @MarsZ in 04/20/2017 16:20:24
 /// </summary>
public static class ProxyBattleFightPreviewModule
{
    public static void Open(PreviewVideo pPreviewVideo)
	{
        var controller = UIModuleManager.Instance.OpenFunModule<BattleFightPreviewController>(BattleFightPreviewView.NAME,UILayerType.DefaultModule,false);
        controller.Open(pPreviewVideo);
	}

	public static void Hide()
	{
        UIModuleManager.Instance.HideModule(BattleFightPreviewView.NAME);	
	}
	
	public static void Close()
	{
        UIModuleManager.Instance.CloseModule(BattleFightPreviewView.NAME);
	}
}