// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuildMemItem : BaseView
{
    public const string NAME ="GuildMemItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite Background_UISprite;
    public UIButton GuildMemItem_UIButton;
    public UISprite campIcon_UISprite;
    public UILabel NameLabel_UILabel;
    public UILabel lvLabel_UILabel;
    public UILabel jobLabel_UILabel;
    public UILabel contributionLabel_UILabel;
    public UILabel onlineLabel_UILabel;
    public GameObject selGo;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Background_UISprite = root.FindScript<UISprite>("Background");
        GuildMemItem_UIButton = root.FindScript<UIButton>("");
        campIcon_UISprite = root.FindScript<UISprite>("campIcon");
        NameLabel_UILabel = root.FindScript<UILabel>("NameLabel");
        lvLabel_UILabel = root.FindScript<UILabel>("lvLabel");
        jobLabel_UILabel = root.FindScript<UILabel>("jobLabel");
        contributionLabel_UILabel = root.FindScript<UILabel>("contributionLabel");
        onlineLabel_UILabel = root.FindScript<UILabel>("onlineLabel");
        selGo = root.FindGameObject("selGo");

    }
    #endregion
}
