// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ScheduleRewardBackItem : BaseView
{
    public const string NAME ="ScheduleRewardBackItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite NameBg_UISprite;
    public UILabel Name_UILabel;
    public UILabel ExpNum_UILabel;
    public UILabel TimeNum_UILabel;
    public UIButton PrefectBackBtn_UIButton;
    public UIButton NormalBackBtn_UIButton;
    public UIButton finishedBtn_UIButton;
    public UISprite PerfectCost_UISprite;
    public UISprite NormalCost_UISprite;
    public UILabel PrefectCost_UILabel;
    public UILabel NormalCost_UILabel;
    public UIGrid Grid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        NameBg_UISprite = root.FindScript<UISprite>("NameBg");
        Name_UILabel = root.FindScript<UILabel>("NameBg/Name");
        ExpNum_UILabel = root.FindScript<UILabel>("Exp/ExpNum");
        TimeNum_UILabel = root.FindScript<UILabel>("Time/TimeNum");
        PrefectBackBtn_UIButton = root.FindScript<UIButton>("PrefectBackBtn");
        NormalBackBtn_UIButton = root.FindScript<UIButton>("NormalBackBtn");
        finishedBtn_UIButton = root.FindScript<UIButton>("finished");
        PerfectCost_UISprite = root.FindScript<UISprite>("PrefectBackBtn/Sprite");
        NormalCost_UISprite = root.FindScript<UISprite>("NormalBackBtn/Sprite");
        PrefectCost_UILabel = root.FindScript<UILabel>("PrefectBackBtn/Cost");
        NormalCost_UILabel = root.FindScript<UILabel>("NormalBackBtn/Cost");
        Grid_UIGrid = root.FindScript<UIGrid>("Grid");

    }
    #endregion
}
