// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ScheduleActivityRemindView : BaseView
{
    public const string NAME ="ScheduleActivityRemindView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UIGrid Grid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("CloseBtn");
        Grid_UIGrid = root.FindScript<UIGrid>("ScrollView/Grid");

    }
    #endregion
}
