// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ScheduleRewardBackView : BaseView
{
    public const string NAME ="ScheduleRewardBackView";

    #region Element Bindings

    /// bind gameobject
    public UIButton TipsBtn_UIButton;
    public UIGrid Grid_UIGrid;
    public UIButton WeekBtn_UIButton;
    public UIButton PushBtn_UIButton;
    public UIButton OneKeyBackBtn_UIButton;
    public UIButton PrefectBackBtn_UIButton;
    public UISprite OneKeyNormmalBack_UISprite;
    public UISprite OneKeyPerfectBack_UISprite;
    public UISprite normal_UISprite;
    public UISprite perfect_UISprite;
    public BoxCollider normal_BoxCollider;
    public BoxCollider perfect_BoxCollider;

    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TipsBtn_UIButton = root.FindScript<UIButton>("TipsBtn");
        Grid_UIGrid = root.FindScript<UIGrid>("Bg/ScrollView/Grid");
        WeekBtn_UIButton = root.FindScript<UIButton>("WeekBtn");
        PushBtn_UIButton = root.FindScript<UIButton>("PushBtn");
        OneKeyBackBtn_UIButton = root.FindScript<UIButton>("OneKeyBackBtn");
        PrefectBackBtn_UIButton = root.FindScript<UIButton>("PrefectBackBtn");
        OneKeyNormmalBack_UISprite = root.FindScript<UISprite>("OneKeyBackBtn/Sprite");
        OneKeyPerfectBack_UISprite = root.FindScript<UISprite>("PrefectBackBtn/Sprite");
        normal_UISprite = root.FindScript<UISprite>("OneKeyBackBtn");
        perfect_UISprite = root.FindScript<UISprite>("PrefectBackBtn");
        normal_BoxCollider = root.FindScript<BoxCollider>("OneKeyBackBtn");
        perfect_BoxCollider = root.FindScript<BoxCollider>("PrefectBackBtn");

    }
    #endregion
}
