// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ScheduleActivityRemindItem : BaseView
{
    public const string NAME ="ScheduleActivityRemindItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel Name_UILabel;
    public UILabel Date_UILabel;
    public UILabel Time_UILabel;
    public UISprite SwitchOn_UISprite;
    public UISprite SwitchOff_UISprite;
    public UIButton Btn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Name_UILabel = root.FindScript<UILabel>("Name");
        Date_UILabel = root.FindScript<UILabel>("Date");
        Time_UILabel = root.FindScript<UILabel>("Time");
        SwitchOn_UISprite = root.FindScript<UISprite>("SwitchOn");
        SwitchOff_UISprite = root.FindScript<UISprite>("SwitchOff");
        Btn_UIButton = root.FindScript<UIButton>("Btn");

    }
    #endregion
}
