// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ScheduleDailyView : BaseView
{
    public const string NAME ="ScheduleDailyView";

    #region Element Bindings

    /// bind gameobject
    public UIButton TipsBtn_UIButton;
    public UIGrid BtnGrid_UIGrid;
    public UIGrid Grid_UIGrid;
    public UILabel ActiveNum_UILabel;
    public UIGrid RewardGrid_UIGrid;
    public UISlider ActiveNumSlider_UISlider;
    public UIButton WeekBtn_UIButton;
    public UIButton PushBtn_UIButton;
    public UIScrollView ScrollView_UIScrollView;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TipsBtn_UIButton = root.FindScript<UIButton>("TipsBtn");
        BtnGrid_UIGrid = root.FindScript<UIGrid>("BtnGrid");
        Grid_UIGrid = root.FindScript<UIGrid>("Bg/ScrollView/Grid");
        ActiveNum_UILabel = root.FindScript<UILabel>("Progress/ActiveNum");
        RewardGrid_UIGrid = root.FindScript<UIGrid>("Progress/RewardGrid");
        ActiveNumSlider_UISlider = root.FindScript<UISlider>("Progress/ActiveNumSlider");
        WeekBtn_UIButton = root.FindScript<UIButton>("WeekBtn");
        PushBtn_UIButton = root.FindScript<UIButton>("PushBtn");
        ScrollView_UIScrollView = root.FindScript<UIScrollView>("Bg/ScrollView");

    }
    #endregion
}
