// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class AssistFriendItem : BaseView
{
    public const string NAME ="AssistFriendItem";

    #region Element Bindings

    /// bind gameobject
    public UISprite Icon_UISprite;
    public UILabel Name_UILabel;
    public UIButton InviteBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Icon_UISprite = root.FindScript<UISprite>("IconBg/Icon");
        Name_UILabel = root.FindScript<UILabel>("Name");
        InviteBtn_UIButton = root.FindScript<UIButton>("InviteBtn");

    }
    #endregion
}
