// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class AssistDelegateMissionBtn : BaseView
{
    public const string NAME ="AssistDelegateMissionBtn";

    #region Element Bindings

    /// bind gameobject
    public UILabel Label_UILabel;
    public UISprite ChoseBg_UISprite;
    public UISprite LvStar_1_UISprite;
    public UISprite LvStar_2_UISprite;
    public UISprite LvStar_3_UISprite;
    public UISprite LvStar_4_UISprite;
    public UISprite LvStar_5_UISprite;
    public UISprite IngBg_UISprite;
    public UISprite CompleteBg_UISprite;
    public UISprite Icon_UISprite;
    public UISprite Sprite_UISprite;
    public UIButton AssistDelegateMissionBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Label_UILabel = root.FindScript<UILabel>("Label");
        ChoseBg_UISprite = root.FindScript<UISprite>("ChoseBg");
        LvStar_1_UISprite = root.FindScript<UISprite>("Stars/LvStar_1");
        LvStar_2_UISprite = root.FindScript<UISprite>("Stars/LvStar_2");
        LvStar_3_UISprite = root.FindScript<UISprite>("Stars/LvStar_3");
        LvStar_4_UISprite = root.FindScript<UISprite>("Stars/LvStar_4");
        LvStar_5_UISprite = root.FindScript<UISprite>("Stars/LvStar_5");
        IngBg_UISprite = root.FindScript<UISprite>("IngBg");
        CompleteBg_UISprite = root.FindScript<UISprite>("CompleteBg");
        Icon_UISprite = root.FindScript<UISprite>("Icon");
        Sprite_UISprite = root.FindScript<UISprite>("Sprite");
        AssistDelegateMissionBtn_UIButton = root.FindScript<UIButton>("");

    }
    #endregion
}
