// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class RecipeTips : BaseView
{
    public const string NAME ="RecipeTips";

    #region Element Bindings

    /// bind gameobject
    public UISprite Bg_UISprite;
    public UILabel Name_UILabel;
    public UIGrid Grid_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Bg_UISprite = root.FindScript<UISprite>("Bg");
        Name_UILabel = root.FindScript<UILabel>("Bg/Name");
        Grid_UIGrid = root.FindScript<UIGrid>("Bg/Grid");

    }
    #endregion
}
