// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class RecipeItemView : BaseView
{
    public const string NAME ="RecipeItemView";

    #region Element Bindings

    /// bind gameobject
    public UISprite RecepeIcon_UISprite;
    public UILabel RecepeName_UILabel;
    public UIButton Item_1_UIButton;
    public UIButton Item_2_UIButton;
    public UIButton Item_3_UIButton;
    public UIButton Item_4_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        RecepeIcon_UISprite = root.FindScript<UISprite>("RecipeBg/RecepeIcon");
        RecepeName_UILabel = root.FindScript<UILabel>("RecepeName");
        Item_1_UIButton = root.FindScript<UIButton>("Table/Item_1");
        Item_2_UIButton = root.FindScript<UIButton>("Table/Item_2");
        Item_3_UIButton = root.FindScript<UIButton>("Table/Item_3");
        Item_4_UIButton = root.FindScript<UIButton>("Table/Item_4");

    }
    #endregion
}
