// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class GuildHasJoinView : BaseView
{
    public const string NAME ="GuildHasJoinView";

    #region Element Bindings

    /// bind gameobject
    public UITable TabGrid_UIGrid;
    public UIButton CloseBtn_UIButton;
    public GameObject InfoView;
    public GameObject ManagerView;
    public GameObject ActivityView;
    public GameObject WelfareView;
    public GameObject BuildingView;
   
    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TabGrid_UIGrid = root.FindScript<UITable>("BaseMainWindow/TabGroup");
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseMainWindow/CloseBtn");
        InfoView = root.FindGameObject("InfoView");
        ManagerView = root.FindGameObject("ManagerView");
        ActivityView = root.FindGameObject("ActivityView");
        WelfareView = root.FindGameObject("WelfareView");
        BuildingView = root.FindGameObject("BuildingView");
    }
    #endregion
}
