// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewFavorLabel : BaseView
{
    public const string NAME ="CrewFavorLabel";

    #region Element Bindings

    /// bind gameobject
    public UILabel Grade_UILabel;
    public UILabel Content_UILabel;
    public UILabel Desc_UILabel;
    public UISprite Sprite_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Grade_UILabel = root.FindScript<UILabel>("Grade");
        Content_UILabel = root.FindScript<UILabel>("Content");
        Desc_UILabel = root.FindScript<UILabel>("Desc");
        Sprite_UISprite = root.FindScript<UISprite>("Sprite");

    }
    #endregion
}
