// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class AssistLearnCookView : BaseView
{
    public const string NAME ="AssistLearnCookView";

    #region Element Bindings

    /// bind gameobject
    public UILabel TitleTip_UILabel;
    public UIGrid Grid_UIGrid;
    public UIButton NoBtn_UIButton;
    public UIButton YesBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        TitleTip_UILabel = root.FindScript<UILabel>("TitleTip");
        Grid_UIGrid = root.FindScript<UIGrid>("Grid");
        NoBtn_UIButton = root.FindScript<UIButton>("NoBtn");
        YesBtn_UIButton = root.FindScript<UIButton>("YesBtn");

    }
    #endregion
}
