// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  MainUIExpandContentViewController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface IMainUIExpandContentViewController
{
     UniRx.IObservable<Unit> OnTabBtn_Task_UIButtonClick{get;}
     UniRx.IObservable<Unit> OncancelMatchBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnjoinOrLeaveBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OncallOrAwayBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnteamMsgBtn_UIButtonClick{get;}
     UniRx.IObservable<Unit> OnTeamRequestBtnClick{get;}
     UniRx.IObservable<Unit> OnTabBtn_Team_UIButtonClick{get;}

}

public partial class MainUIExpandContentViewController:MonolessViewController<MainUIExpandContentView>, IMainUIExpandContentViewController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        TabBtn_Task_UIButtonEvt = View.TabBtn_Task_UIButton.AsObservable();
        cancelMatchBtn_UIButtonEvt = View.cancelMatchBtn_UIButton.AsObservable();
        joinOrLeaveBtn_UIButtonEvt = View.joinOrLeaveBtn_UIButton.AsObservable();
        callOrAwayBtn_UIButtonEvt = View.callOrAwayBtn_UIButton.AsObservable();
        teamMsgBtn_UIButtonEvt = View.teamMsgBtn_UIButton.AsObservable();
        TeamRequestBtnEvt = View.TeamRequestBtn.AsObservable();
        TabBtn_Team_UIButtonEvt = View.TabBtn_Team_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        TabBtn_Task_UIButtonEvt = TabBtn_Task_UIButtonEvt.CloseOnceNull();
        cancelMatchBtn_UIButtonEvt = cancelMatchBtn_UIButtonEvt.CloseOnceNull();
        joinOrLeaveBtn_UIButtonEvt = joinOrLeaveBtn_UIButtonEvt.CloseOnceNull();
        callOrAwayBtn_UIButtonEvt = callOrAwayBtn_UIButtonEvt.CloseOnceNull();
        teamMsgBtn_UIButtonEvt = teamMsgBtn_UIButtonEvt.CloseOnceNull();
        TeamRequestBtnEvt = TeamRequestBtnEvt.CloseOnceNull();
        TabBtn_Team_UIButtonEvt = TabBtn_Team_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> TabBtn_Task_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTabBtn_Task_UIButtonClick{
        get {return TabBtn_Task_UIButtonEvt;}
    }

    private Subject<Unit> cancelMatchBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OncancelMatchBtn_UIButtonClick{
        get {return cancelMatchBtn_UIButtonEvt;}
    }

    private Subject<Unit> joinOrLeaveBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnjoinOrLeaveBtn_UIButtonClick{
        get {return joinOrLeaveBtn_UIButtonEvt;}
    }

    private Subject<Unit> callOrAwayBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OncallOrAwayBtn_UIButtonClick{
        get {return callOrAwayBtn_UIButtonEvt;}
    }

    private Subject<Unit> teamMsgBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnteamMsgBtn_UIButtonClick{
        get {return teamMsgBtn_UIButtonEvt;}
    }

    private Subject<Unit> TeamRequestBtnEvt;
    public UniRx.IObservable<Unit> OnTeamRequestBtnClick{
        get {return TeamRequestBtnEvt;}
    }

    private Subject<Unit> TabBtn_Team_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTabBtn_Team_UIButtonClick{
        get {return TabBtn_Team_UIButtonEvt;}
    }


}
