// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewPassiveTypeBtn : BaseView
{
    public const string NAME ="CrewPassiveTypeBtn";

    #region Element Bindings

    /// bind gameobject
    public UIButton CrewPassiveTypeBtn_UIButton;
    public UISprite SelectSprite_UISprite;
    public UILabel TypeNameLbl_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CrewPassiveTypeBtn_UIButton = root.FindScript<UIButton>("");
        SelectSprite_UISprite = root.FindScript<UISprite>("SelectSprite");
        TypeNameLbl_UILabel = root.FindScript<UILabel>("TypeNameLbl");

    }
    #endregion
}
