// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewSkillItem : BaseView
{
    public const string NAME ="CrewSkillItem";

    #region Element Bindings

    /// bind gameobject
    public UIButton CrewSkillItem_UIButton;
    public UISprite AddIcon_UISprite;
    public UITexture SkillIcon_UITexture;
    public UISprite bookMark_UISprite;
    public UILabel NumLbl_UILabel;
    public UISprite ArrowsMark_UISprite;
    public UISprite LevelMark_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CrewSkillItem_UIButton = root.FindScript<UIButton>("");
        AddIcon_UISprite = root.FindScript<UISprite>("AddIcon");
        SkillIcon_UITexture = root.FindScript<UITexture>("SkillIcon");
        bookMark_UISprite = root.FindScript<UISprite>("bookMark");
        NumLbl_UILabel = root.FindScript<UILabel>("NumLbl");
        ArrowsMark_UISprite = root.FindScript<UISprite>("ArrowsMark");
        LevelMark_UISprite = root.FindScript<UISprite>("LevelMark");

    }
    #endregion
}
