// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewSkillMagicTips : BaseView
{
    public const string NAME ="CrewSkillMagicTips";

    #region Element Bindings

    /// bind gameobject
    public UIButton btnUp_UIButton;
    public Transform rangeTrans_Transform;
    public UITexture itemIcon_UISprite;
    public Transform IsSIcon_Transform;
    public UILabel lblGrade_UILabel;
    public UISprite bg_UISprite;
    public UILabel lblType_UILabel;
    public UILabel lblName_UILabel;
    public UILabel lblEff_UILabel;
    public UILabel lblAfter_UILabel;
    public UILabel lblBefor_UILabel;
    public UILabel lblCp_UILabel;
    public UILabel lblType2_UILabel;
    public UILabel lblScope_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        btnUp_UIButton = root.FindScript<UIButton>("btnUp");
        rangeTrans_Transform = root.FindTrans("rangeTrans");
        itemIcon_UISprite = root.FindScript<UITexture>("item/itemIcon");
        IsSIcon_Transform = root.FindTrans("item/IsSIcon");
        lblGrade_UILabel = root.FindScript<UILabel>("item/lblGrade");
        bg_UISprite = root.FindScript<UISprite>("item/bg");
        lblType_UILabel = root.FindScript<UILabel>("lblType");
        lblName_UILabel = root.FindScript<UILabel>("lblName");
        lblEff_UILabel = root.FindScript<UILabel>("lblEff");
        lblAfter_UILabel = root.FindScript<UILabel>("lblAfter");
        lblBefor_UILabel = root.FindScript<UILabel>("lblBefor");
        lblCp_UILabel = root.FindScript<UILabel>("lblCp");
        lblType2_UILabel = root.FindScript<UILabel>("lblType2");
        lblScope_UILabel = root.FindScript<UILabel>("lblScope");

    }
    #endregion
}
