// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewSkillCraftsView : BaseView
{
    public const string NAME ="CrewSkillCraftsView";

    #region Element Bindings

    /// bind gameobject
    public UIGrid ItemList_UIGrid;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ItemList_UIGrid = root.FindScript<UIGrid>("ItemList");

    }
    #endregion
}
