// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewSkillItemCell : BaseView
{
    public const string NAME ="CrewSkillItemCell";

    #region Element Bindings

    /// bind gameobject
    public UILabel lblNum_UILabel;
    public UILabel lblGrade_UILabel;
    public Transform spSelected_Transform;
    public UISprite spIcon_UISprite;
    public UITexture spIcon_Tex;
    public Transform isS_Transform;
    public UILabel lblRewardNum_UILabel;
    public UISprite bg_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        lblNum_UILabel = root.FindScript<UILabel>("lblNum");
        lblGrade_UILabel = root.FindScript<UILabel>("lblGrade");
        spSelected_Transform = root.FindTrans("spSelected");
        spIcon_UISprite = root.FindScript<UISprite>("spIcon");
        spIcon_Tex = root.FindScript<UITexture>("spIcoTex");
        isS_Transform = root.FindTrans("isS");
        lblRewardNum_UILabel = root.FindScript<UILabel>("lblRewardNum");
        bg_UISprite = root.FindScript<UISprite>("bg");

    }
    #endregion
}
