// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class CrewCraftSkillView : BaseView
{
    public const string NAME ="CrewCraftSkillView";

    #region Element Bindings

    /// bind gameobject
    public Transform SkillIconGroup_Transform;
    public UILabel SkillLevelLbl_UILabel;
    public UILabel SkillNameLbl_UILabel;
    public UILabel SkillTypeLbl_UILabel;
    public UILabel SkillAfterLbl_UILabel;
    public UILabel SkillNatureLbl_UILabel;
    public UILabel SkillLimitLbl_UILabel;
    public UILabel SkillScopeLbl_UILabel;
    public UILabel SkillConsumeLbl_UILabel;
    public Transform rangeTrans_Transform;
    public UILabel SkillEffectLabel_UILabel;
    public UIButton SkillUpgradeBtn_UIButton;
    public UIGrid MaterialGrid_UIGrid;
    public UILabel SkillBeforeLbl_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        SkillIconGroup_Transform = root.FindTrans("Content/SkillIconGroup");
        SkillLevelLbl_UILabel = root.FindScript<UILabel>("Content/SkillLevelLbl");
        SkillNameLbl_UILabel = root.FindScript<UILabel>("Content/SkillNameLbl");
        SkillTypeLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillType/SkillTypeLbl");
        SkillAfterLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillAfter/SkillAfterLbl");
        SkillNatureLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillNature/SkillNatureLbl");
        SkillLimitLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillLimit/SkillLimitLbl");
        SkillScopeLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillScope/SkillScopeLbl");
        SkillConsumeLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillConsume/SkillConsumeLbl");
        rangeTrans_Transform = root.FindTrans("Content/SkillDescripeGroup/rangeTrans");
        SkillEffectLabel_UILabel = root.FindScript<UILabel>("Content/SkillEffect/SkillEffectLabel");
        SkillUpgradeBtn_UIButton = root.FindScript<UIButton>("Content/MaterialConsume/SkillUpgradeBtn");
        MaterialGrid_UIGrid = root.FindScript<UIGrid>("Content/MaterialConsume/MaterialGrid");
        SkillBeforeLbl_UILabel = root.FindScript<UILabel>("Content/SkillDescripeGroup/SkillBefore/SkillBeforeLbl");

    }
    #endregion
}
