// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class CrewSkillMagicView : BaseView
{
    public const string NAME ="CrewSkillMagicView";

    #region Element Bindings

    /// bind gameobject
    public UIButton btnDLQ_UIButton;
    public UILabel lblCraftsName_UILabel;
    public UILabel lblDesc_UILabel;
    public Transform rangePos_Transform;
    public UISprite itemIcon_UISprite;
    public UIGrid ItemList_Transform;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        btnDLQ_UIButton = root.FindScript<UIButton>("btnDLQ");
        lblCraftsName_UILabel = root.FindScript<UILabel>("RightTips/lblCraftsName");
        lblDesc_UILabel = root.FindScript<UILabel>("RightTips/lblDesc");
        rangePos_Transform = root.FindTrans("RightTips/rangePos");
        itemIcon_UISprite = root.FindScript<UISprite>("RightTips/itemIcon");
        ItemList_Transform = root.FindScript<UIGrid>("ItemList");

    }
    #endregion
}
