// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed partial class MissionTypeItem : BaseView
{
    public const string NAME ="MissionTypeItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel lbltype_UILabel;
    public UIGrid tween_UIGrid;
    public UIButton MissionTypeItem_UIButton;
    public Transform pool_Transform;
    public UISprite bg_UISprite;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        lbltype_UILabel = root.FindScript<UILabel>("lbltype");
        tween_UIGrid = root.FindScript<UIGrid>("tween");
        pool_Transform = root.FindTrans("pool");
        MissionTypeItem_UIButton = root.FindScript<UIButton>("");
        bg_UISprite = root.FindScript<UISprite>("bg");
    }
    #endregion
}
