// **********************************************************************
// Copyright (c)  Baoyugame. All rights reserved.
// File     :  TradeOptionBtnController.cs
// the file is generated by tools
// **********************************************************************


using UniRx;

public partial interface ITradeOptionBtnController
{
     UniRx.IObservable<Unit> OnTradeOptionBtn_UIButtonClick{get;}

}

public partial class TradeOptionBtnController:MonolessViewController<TradeOptionBtn>, ITradeOptionBtnController
{
    //机器自动生成的事件绑定
    protected override void InitReactiveEvents(){
        TradeOptionBtn_UIButtonEvt = View.TradeOptionBtn_UIButton.AsObservable();

    }

    protected override void ClearReactiveEvents(){
        TradeOptionBtn_UIButtonEvt = TradeOptionBtn_UIButtonEvt.CloseOnceNull();

    }

    private Subject<Unit> TradeOptionBtn_UIButtonEvt;
    public UniRx.IObservable<Unit> OnTradeOptionBtn_UIButtonClick{
        get {return TradeOptionBtn_UIButtonEvt;}
    }


}
