//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AgreementView.
/// </summary>
public partial class AgreementView : BaseView
{
	public const string NAME ="AgreementView";
	public UIButton CloseButton_UIButton;
	public UIButton LeftArrowSprite_UIButton;
	public UIButton RightArrowSprite_UIButton;
	public UILabel PageLabel_UILabel;
	public UILabel ContentLabel_UILabel;
	public UIButton SubmitBtn_UIButton;
	public UIScrollView scrollView_UIScrollView;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		CloseButton_UIButton = root.Find("BaseWindow/CloseBtn").GetComponent<UIButton>();
		LeftArrowSprite_UIButton = root.Find("BgSprite/PageGroup/LeftArrowSprite").GetComponent<UIButton>();
		RightArrowSprite_UIButton = root.Find("BgSprite/PageGroup/RightArrowSprite").GetComponent<UIButton>();
		PageLabel_UILabel = root.Find("BgSprite/PageGroup/PageLabel").GetComponent<UILabel>();
		ContentLabel_UILabel = root.Find("BgSprite/scrollView/ContentLabel").GetComponent<UILabel>();
		SubmitBtn_UIButton = root.Find("BgSprite/SubmitBtn").GetComponent<UIButton>();
		scrollView_UIScrollView = root.Find("BgSprite/scrollView").GetComponent<UIScrollView>();
	}
}
