// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class ItemQuickBuyView : BaseView
{
    public const string NAME ="ItemQuickBuyView";

    #region Element Bindings

    /// bind gameobject
    public UIButton CloseBtn_UIButton;
    public UISprite PropsIcon_UISprite;
    public UISprite CashIcon_UISprite;
    public UILabel ParopNameLb_UILabel;
    public UILabel DescLb_UILabel;
    public UIButton ReduceBtn_UIButton;
    public UIButton AddBtn_UIButton;
    public UIButton MaxBtn_UIButton;
    public UILabel NumLb_UILabel;
    public UILabel CashLb_UILabe;
    public UILabel HadCashLb1_UILabel;
    public UILabel HadCashLb2_UILabel;
    public UIButton BuyBtn_UIButton;
    public BoxCollider BuyBtn_BoxCollider;
    public UIButton LastBtn_UIButton;
    public UIButton NextBtn_UIButton;
    public UISprite CashIcon1_UISprite;
    public UISprite CashIcon2_UISprite;
    public UISprite IconBG_UISprite;
    public UILabel Title_UILabel;
    public UIButton SimpleBtn_UIButton;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        CloseBtn_UIButton = root.FindScript<UIButton>("BaseWindow/CloseBtn");
        PropsIcon_UISprite = root.FindScript<UISprite>("MainContent/PropsIcon");
        CashIcon_UISprite = root.FindScript<UISprite>("MainContent/NeedCash/CashIcon");
        ParopNameLb_UILabel = root.FindScript<UILabel>("MainContent/ParopNameLb");
        DescLb_UILabel = root.FindScript<UILabel>("MainContent/DescLb");
        ReduceBtn_UIButton = root.FindScript<UIButton>("MainContent/ReduceBtn");
        AddBtn_UIButton = root.FindScript<UIButton>("MainContent/AddBtn");
        MaxBtn_UIButton = root.FindScript<UIButton>("MainContent/MaxBtn");
        NumLb_UILabel = root.FindScript<UILabel>("MainContent/Num/NumLb");
        CashLb_UILabe = root.FindScript<UILabel>("MainContent/NeedCash/CashLb");
        HadCashLb1_UILabel = root.FindScript<UILabel>("MainContent/HadCash/HadCashLb1");
        HadCashLb2_UILabel = root.FindScript<UILabel>("MainContent/HadCash/HadCashLb2");
        BuyBtn_UIButton = root.FindScript<UIButton>("MainContent/BuyBtn");
        BuyBtn_BoxCollider = root.FindScript<BoxCollider>("MainContent/BuyBtn");
        LastBtn_UIButton = root.FindScript<UIButton>("MainContent/LastBtn");
        NextBtn_UIButton = root.FindScript<UIButton>("MainContent/NextBtn");
        CashIcon1_UISprite = root.FindScript<UISprite>("MainContent/HadCash/CashIcon1");
        CashIcon2_UISprite = root.FindScript<UISprite>("MainContent/HadCash/CashIcon2");
        IconBG_UISprite = root.FindScript<UISprite>("MainContent/PropsIcon/IconBG");
        Title_UILabel = root.FindScript<UILabel>("BaseWindow/Title");
        SimpleBtn_UIButton = root.FindScript<UIButton>("MainContent/Num/SimpleBtn");

    }
    #endregion
}
