// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class TextTipsView : BaseView
{
    public const string NAME ="TextTipsView";

    #region Element Bindings

    /// bind gameobject
    public UISprite Bg_UISprite;
    public UILabel Text_UILabel;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        Bg_UISprite = root.FindScript<UISprite>("Bg");
        Text_UILabel = root.FindScript<UILabel>("Bg/Text");

    }
    #endregion
}
