// ------------------------------------------------------------------------------
//  This code is generated by a tool
// ------------------------------------------------------------------------------

using UnityEngine;

public sealed class TipsEquipmentEffectItem : BaseView
{
    public const string NAME ="TipsEquipmentEffectItem";

    #region Element Bindings

    /// bind gameobject
    public UILabel ProLabel_UILabel;
    public UIButton Btn_UIButton;
    public UILabel Des_UILabel;
    public UIWidget TipsEquipmentEffectItem_UIWidget;


    protected override void InitElementBinding ()
    {
	    var root = this.gameObject;
        ProLabel_UILabel = root.FindScript<UILabel>("ProLabel");
        Btn_UIButton = root.FindScript<UIButton>("Btn");
        Des_UILabel = root.FindScript<UILabel>("Des");
        TipsEquipmentEffectItem_UIWidget = root.FindScript<UIWidget>("");

    }
    #endregion
}
