//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for QRCodePayView.
/// </summary>
public partial class QRCodePayView : BaseView
{
	public UILabel Title_UILabel;
	public UITexture QRTexture_UITexture;
	public UIButton EnsureBtn_UIButton;
	public Transform OverTimeGroup_Transform;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		Title_UILabel = root.Find("WaitScanGroup/Title").GetComponent<UILabel>();
		QRTexture_UITexture = root.Find("WaitScanGroup/QRTexture").GetComponent<UITexture>();
		EnsureBtn_UIButton = root.Find("WaitScanGroup/EnsureBtn").GetComponent<UIButton>();
		OverTimeGroup_Transform = root.Find("WaitScanGroup/OverTimeGroup");
	}
}
